local BB = MABabel
--[[ 
BB.AddonList[""] = function() if not  then return false end
return true end

do if not BB.SV.BanList[""] then
end end
BB.AddonList[""] = function() if not  then return false end
return true end
]]

BB.AddonList["BanditsUserInterface"] = function() if not BUI then return false end
  --\lang\en.lua
  local on,off	="开启","关闭"
  local lmb,rmb,mmb='|t16:16:/BanditsUserInterface/textures/lmb.dds|t','|t16:16:/BanditsUserInterface/textures/rmb.dds|t','|t16:16:/BanditsUserInterface/textures/mmb.dds|t'
  local AlignValues	={[8]="左",[128]="中",[2]="右"}
  local default="默认: "
  local TauntTimerValues	={"进程条","条和数字","只有数字","禁用"}
  local ReticleResistValues	={"当前值","详细信息","禁用"}
  local CastBarValues	={"任何技能","施放时间技能","禁用"}

  --KEYBINDINGS
  ZO_CreateStringId("SI_BINDING_NAME_BUI_DISMISS_ALL", "解散所有宠物")
  ZO_CreateStringId("SI_BINDING_NAME_DISPLAY_DAMAGE_REPORT_WINDOW",	"显示伤害报告")
  ZO_CreateStringId("SI_BINDING_NAME_POST_DAMAGE_RESULTS_TO_CHAT",	"贴出伤害结果")
  ZO_CreateStringId("SI_BINDING_NAME_RESET_FIGHT",			"重置当前战斗")
  ZO_CreateStringId("SI_BINDING_NAME_SHOW_LOG",				"展示日志")
  ZO_CreateStringId("SI_BINDING_NAME_TOGGLE_MINIMAP",			"小地图 开/关")
  ZO_CreateStringId("SI_BINDING_NAME_TOGGLE_COMPASS",			"罗盘 开/关")
  ZO_CreateStringId("SI_BINDING_NAME_REGROUPER_REINVITE",		"再次邀请组队")
  ZO_CreateStringId("SI_BINDING_NAME_REGROUPER_REGROUP",		"再次组队")
  
  --QuickSlots
  ZO_CreateStringId("SI_BINDING_NAME_BUI_QUICKSLOT_NEXT",		"快捷槽下一个")
  ZO_CreateStringId("SI_BINDING_NAME_BUI_QUICKSLOT_PREV",		"快捷槽上一个")
  for i	=1,8 do ZO_CreateStringId("SI_BINDING_NAME_BUI_QUICKSLOT_"..i,	"快捷槽 "..i) end
  for i	=1,6 do ZO_CreateStringId("SI_BINDING_NAME_BUI_CUSTOMSLOT_"..i,	"自定义槽 "..i) end
  
  --Automation
  ZO_CreateStringId("SI_KEYBIND_STRIP_FILLET_FISH","切片所有鱼肉")
  ZO_CreateStringId("SI_KEYBIND_STRIP_OPEN_CONTAINERS","打开所有容器")
  ZO_CreateStringId("SI_BINDING_NAME_SIEGECAMERATOGGLE", "切换攻城武器视角")

  BUI.Localization.zh={
    --TOOLTIPS
    MiniMeterDPSToolTip=	lmb	.." 显示伤害报告\n"
              ..	rmb	.." 贴出伤害结果\n"
              ..	mmb	.." 重置当前战斗",
    MiniMeterHPSToolTip=	lmb	.." 显示治疗助手",
    MiniMeterGDPSToolTip1=	lmb	.." 显示队伍报告",
    MiniMeterGDPSToolTip2=	rmb	.." 贴出队伍DPS",
    GroupSectionDpsToolTip=	lmb	.." 显示队伍dps\n"
              ..	rmb	.." 贴出队伍dps",
    GroupSectionRergouperToolTip=	lmb	.." 重新组队\n"
              ..	rmb	.." 保存队伍列表\n"
              ..	mmb	.." 贴出队伍列表",
    GroupSectionResetup	=lmb	..' 重置组队框架',
    GroupSectionDisband	=lmb	..' 解散队伍',
    HelperToolTip=
      "测试长度: 1 分钟\n"
      .."\n"
      .."需要:\n"
      .."保证所列buff在自己身上\n"
      .."保证所列debuff在假人身上\n"
      .."对假人使用所列技能\n"
      .."\n"
      .."开始测试: 使用轻击",

    --UI texts
    MiniMap_Label	="小地图",
    PF_Label	="玩家框架",
    TF_Label	="目标框架",
    GF_Label	="组队框架",
    RF_Label	="团队框架",
    BF_Label	="Boss框架",
    NotP_Label	="主要提醒",
    NotS_Label	="次要提醒",
    Dead	="死亡",
    Offline	="掉线",
    PBuffsLabel	="玩家Buff",
    CBuffsLabel	="自定义Buff",
    SBuffsLabel	="系统技能冷却",
    PasBuffsLabel	="P\na\ns\ns\ni\nv\ne",
    TBuffsLabel	="目标Buff",
    GroupDPS	="队伍DPS",
    Apply		="应用",
    Delete	="删除",
    Save		="保存",

    --Damage Report UI
    DReport	="伤害报告",
    RTracker	="循环追踪",
    HReport	="治疗报告",
    PReport	="获得资源",
    IReport	="受到伤害",
    NoDamage	="没有数据可报告!",
    AllTargets	="所有目标",
    Ability	="技能",
    Crit	="暴击",
    Average	="平均",
    Max	="最大",
    Hit	="暴击/攻击",
    Damage	="伤害",
    Healing	="治疗",
    Power	="资源",
    DPS	="DPS",
    HPS	="HPS",
    NoDPSToReport	="无队伍DPS可报告!",
    NoDamageToReport	="无伤害或治疗可报告!",
    ReportDesc	="|t22:27:/esoui/art/chatwindow/chat_notification_up.dds|t 贴出dps到聊天窗口\n|t22:22:/esoui/art/tutorial/smithing_rightarrow_up.dds|t 包括目标buff\n|t22:22:/esoui/art/buttons/pointsplus_up.dds|t 包括目标伤害\n  |c33BB33v|r  被玩家施放",
    ReportEinfo	="装备信息",
    ReportPBHeader	="玩家buff持续时间",
    ReportTBHeader	="目标buff持续时间",
    ReportBuffHeader	="Buff",
    ReportTimeHeader	="时间 ",
    ReportTargetName	="目标名称",
    ReportTotalDamage	="总伤害",
    ReportCount	="计数",
    ReportTotal	="总共",
    Boss	="Boss",

    --Notifications
    GroupNeedOrbs	="你的队伍需要宝珠!",
    TankNeedShard	="坦克需要碎片!",
    Horn	="号角!",
    Colossus	="巨像!",
    GroupMemberDead	="死亡了!",
    GroupMemberLeave	="离开了队伍",
    You	="你 ",
    Food	="需要补充食物",
    Resurrecting	=" 被复活",

    --Buffs dialog
    BuffsAddFail	="尝试添加buff: 错误的buff名称或id。",
    BuffsAdd	="你确定想要添加\n<<1>> 到 <<2>> 吗？",
    BuffsAdded	="<<1>> 被添加到 <<2>>",
    BuffsRemove	="你确定想要\n从 <<2>> 移除 <<1>> 吗？",

    --Warnings
    ReloadUiWarn	="改变此选项的结果将在重载界面后可见。",
    ReloadUiWarn1	="此选项需要重载界面",
    ReloadUiWarn2	="某些改变将在重载界面后生效",
    ReloadUiWarn4	="开启此选项将立即重载界面",
    ReloadUiWarn5	="关闭此选项将立即重载界面",
    PerformanceWarn	="此选项可能会降低游戏性能",
    
    --Reset
    Reset	="重置插件选项",
    ResetDesc	="将整个插件重置为原始设置。",
    ResetPositions	="重置框架",
    ResetPositionsDesc	="重置界面元素的位置。",
    FramesReset	="重置",
    FramesResetDesc	="将玩家, 目标和组队框架重置为原始设置。",
    CurvedReset	="重置",
    CurvedResetDesc	="将弯曲框架重置为原始设置。",
    ColorsReset	="重置",
    ColorsResetDesc	="将字体, 颜色和其他重置为原始设置。",
    StatsReset	="重置",
    StatsResetDesc	="将伤害统计组件重置为原始设置。",
    BuffsReset	="Buff重置",
    BuffsResetDesc	="将增益重置为原始设置。",
    ActionsReset	="重置",
    ActionsResetDesc	="重置为原始设置。",
    MinimapReset	="小地图重置",
    MinimapResetDesc	="将小地图重置为原始设置。",
    
    --Delete
    DeleteMailConfirm ="确认摧毁邮件附带的物品和货币么？",

    --Headers
    MiscHeader	="基本选项",
    MiscHeader1	="其他选项",
    PlayerHeader	="玩家框架",
    CurvedHeader	="弯曲框架",
    GroupHeader	="组队框架",
    StatShareHeader	="组队状态",
    TargetHeader	="目标框架",
    ActionsHeader	="技能计时器",
    BuffsHeader	="增益",
    MinimapHeader	="小地图",
    ReticleHeader	="十字标",
    NotificationsHeader	="提醒",
    NotificationsCombatHeader	="战斗提醒",
    ColorsHeader	="框架设置",
    ActionSlotsHeader	="技能栏",
    QuickSlotsHeader	="快捷栏",
    GroupRolesHeader	="组队角色",
    StatHeader	="伤害统计",
    ZoomHeader	="缩放选项",
    PinColorsHeader	="图标颜色",
    AdvancedHeader	="高级选项",
    AttributeColors	="属性颜色",

    --CustomBar
    CustomBarHeader	="自定义条",
    CustomBar		="自定义条开启",
    LeaderCommands	="队长命令",
    CustomCommands	="自定义命令",
    TextureFilename	="纹理文件名",
    SlashCommand	="输入命令",

    --SidePanel
    PanelHeader	="侧面板",
    PanelEnable	="侧面板开启",
    PanelAllowOther	="允许其他插件使用面板",
    PanelSettings	="Bandits UI 设置",
    PanelStatistics	="战斗统计",
    PanelShare		="状态和DPS分享开关",
    PanelHealerHelper	="治疗者助手",
    PanelGearManager	="装备管理器",
    PanelMinimap	="小地图切换",
    PanelCompass	="3D罗盘",
    PanelLeaderArrow	="队长箭头",
    PanelDismissPets	="解散战斗宠物",
    PanelSubSampling	="二次抽样质量开关",
    PanelVanishPlayers	="虎人模式",
    PanelVanishPlayersDesc	="虎人模式。\n消失掉其他玩家模型。在进入位置之前激活此设置 (例如银行或暗锚).\n再次可见: 禁用然后重新进入位置。",
    PanelWidgets	="管理小工具",
    PanelVeteranDifficulty	="地牢难度",
    PanelLFG_Role	="组队角色",
    PanelBanker	="银行家",
    PanelTrader	="商人",
    PanelSmuggler	="销赃者",
    PanelArmorer	="军械助手",
    PanelRagpicker	="分解助手",
    PanelEvent	="当前事件增益",
    PanelWPamA	="WPamA插件按钮",
    PanelTeleporter	="传送点",
    PanelTeleporterDesc="聊天标签选择器已安装后可使用。",

    --Minimap
    Minimap	="开启小地图",
    MinimapDesc	=default..(BUI.MiniMap.Defaults.MiniMap and on or off),
    MiniMapDimensions	="小地图尺寸",
    MiniMapDimensionsDesc	=default..BUI.MiniMap.Defaults.MiniMapDimensions,
    PinScale	="小地图图标尺寸",
    PinScaleDesc	=default..BUI.MiniMap.Defaults.PinScale.."%",
    MinimapTitle	="位置标题",
    MinimapTitleDesc	=default..(BUI.MiniMap.Defaults.MiniMapTitle and on or off),

    ZoomZone	="区域",
    ZoomZoneDesc	=default..BUI.MiniMap.Defaults.ZoomZone.."%",
    ZoomSubZone	="子区域",
    ZoomSubZoneDesc	=default..BUI.MiniMap.Defaults.ZoomSubZone.."%",
    ZoomDungeon	="地牢",
    ZoomDungeonDesc	=default..BUI.MiniMap.Defaults.ZoomDungeon.."%",
    ZoomCyrodiil	="西罗帝尔",
    ZoomCyrodiilDesc	=default..BUI.MiniMap.Defaults.ZoomCyrodiil.."%",
    ZoomImperialsewer	="帝都下水道",
    ZoomImperialsewerDesc	=default..BUI.MiniMap.Defaults.ZoomImperialsewer.."%",
    ZoomImperialCity	="帝都",
    ZoomImperialCityDesc	=default..BUI.MiniMap.Defaults.ZoomImperialCity.."%",
    ZoomMountRatio	="骑乘比例",
    ZoomMountRatioDesc	="骑乘时的缩放比例\n"..default..BUI.MiniMap.Defaults.ZoomMountRatio.."%",
    ZoomGlobal	="默认地图缩放",
    ZoomGlobalDesc	="为游戏地图定义初始缩放\n"..default..BUI.MiniMap.Defaults.ZoomGlobal.."%",

    --Reticle
    LeaderArrow	="1. 组队队长箭头",
    LeaderArrowDesc	="队长方向和距离箭头\n"..default..(BUI.Defaults.LeaderArrow and on or off),
    InCombatReticle	="2. 十字标战斗提示",
    InCombatReticleDesc	="红色-进入/白色-离开 战斗时。黄色-战斗锁定状态.\n"..default..(BUI.Defaults.InCombatReticle and on or off),
    PreferredTarget	="3. 优先目标锁定",
    PreferredTargetDesc	="当瞄准被设为优先的目标时，十字标改变\n"..default..(BUI.Defaults.PreferredTarget and on or off),
    ReticleDpS	="4. 十字标附近显示当前DpS",
    ReticleDpSDesc	="(仅当开启了\"迷你仪表\"功能时可用)\n"..default..(BUI.Defaults.ReticleDpS and on or off),
    ReticleInvul	="5. 免疫信息",
    ReticleInvulDesc	=default..(BUI.Defaults.ReticleInvul and on or off),
    CrusherTimer	="6. 坦克: 粉碎者计时器",
    CrusherTimerDesc	="(只在目标增益开启时可用)\n"..default..(BUI.Defaults.CrusherTimer and on or off),
    TauntTimer	="7. 坦克: 嘲讽计时器",
    TauntTimerValues	=TauntTimerValues,
    TauntTimerDesc	="(只在目标增益开启时可用)\n"..default..TauntTimerValues[BUI.Defaults.TauntTimer],
    TauntTimerSource	="7. 仅玩家嘲讽",
    TauntTimerSourceDesc=default..(BUI.Defaults.TauntTimerSource and on or off),
    ReticleResist	="8. 目标抗性",
    ReticleResistValues	=ReticleResistValues,
    ReticleResistDesc	="在十字标附近展示目标抗性(只在目标增益开启时可用)。\n"..default..ReticleResistValues[BUI.Defaults.ReticleResist],
    CastBar	="9. 施放条",
    CastBarValues	=CastBarValues,
    CastBarDesc	="(只在 \"技能计时器\"开启时可用)\n"..default..CastBarValues[BUI.Defaults.CastBar],
    SwapIndicator	="10. 切手指示器",
    SwapIndicatorDesc	="(只在 \"技能计时器\"开启时可用)\n"..default..CastBarValues[BUI.Defaults.CastBar],
    ImpactAnimation	="11. 有效击中动画",
    ImpactAnimationDesc	="有效击中时光标动画\n"..default..(BUI.Defaults.ImpactAnimation and on or off),
    ReticleMode	="12. 十字标模式",
    ReticleBoost	="13. 加速指示器",
    ReticleBoostDesc	="(必须开启玩家增益)\n"..default..(BUI.Defaults.ReticleBoost and on or off),
    BlockIndicator	="14. 格挡指示器",

    --ActionSlots
    ActionSlots	="技能栏",
    ActionSlotsDesc	=default..(BUI.Defaults.ActionSlots and on or off),

    --QuickSlots
    QuickSlots	="快捷栏",
    QuickSlotsDesc	=default..(BUI.Defaults.QuickSlots and on or off),
    QuickSlotsShow	="快捷栏数字",
    QuickSlotsShowDesc	="即使快捷栏数字被放置成两行。\n"..default..BUI.Defaults.QuickSlotsShow,
    QuickSlotsInventory	="物品槽",
    QuickSlotsInventoryDesc	="物品栏快捷槽面板。\n"..default..(BUI.Defaults.QuickSlotsInventory and on or off),

    --Notifications
    NotificationsGroup	="组队提醒",
    NotificationsGroupDesc	='"治疗者死亡", "队伍需要宝珠", "坦克需要碎片", "使用号角", etc.\n'..default..(BUI.Defaults.NotificationsGroup and on or off),
    OnScreenPriorDeath	="只在坦克和治疗者死亡时提醒",
    OnScreenPriorDeathDesc	='只在坦克和治疗者死亡时提醒。\n'..default..(BUI.Defaults.OnScreenPriorDeath and on or off),
    NotificationsWorld	="战斗提醒 (世界)",
    NotificationsWorldDesc	='在开放世界和地牢中的战斗提醒: "升天击", "流星", "瞄准射击", "中毒", etc.\n'..default..(BUI.Defaults.NotificationsWorld and on or off),
    NotificationsTrial	="战斗提醒 (试炼)",
    NotificationsTrialDesc	="在试炼中的战斗提醒\n"..default..(BUI.Defaults.NotificationsTrial and on or off),
    NotificationFood		="食物增益提醒",
    NotificationFoodDesc	=default..(BUI.Defaults.NotificationFood and on or off),
    EffectVisualisation	="效果可视化",
    EffectVisualisationDesc	='屏幕边缘变色 中毒变绿, 冰冻变蓝, 超载变亮, \"有害标记\"变紫, 流血变棕, 燃烧变红\n'..default..(BUI.Defaults.EffectVisualisation and on or off),
    NotificationsSize	="字体大小",
    NotificationsSizeDesc	=default..BUI.Defaults.NotificationsSize,
    NotificationsTimer	="延迟",
    NotificationsTimerDesc	=default..BUI.Defaults.NotificationsTimer,
    NotificationSound_1	="主要提醒声音",
    NotificationSound_2	="次要提醒声音",

    --Misc options
    ChangeLanguage	="改变语言（目前由Babel集成汉化，无需修改）",
    ChangeLanguageDesc	="[默认: en]",
    ChangeLanguageWarn	="修改此选项将立即重载界面!",
    Theme	="主题",
    Move	="移动框架",
    MoveDesc	="修改界面元素位置.",
    PlayerStatSection	="玩家信息",
    PlayerStatSectionDesc	="添加: 穿透, 暴击伤害增益, 格挡消耗, 格挡缓和信息到玩家属性区域",
    PvPmode	="PvP模式",
    PvPmodeDesc	="在PVP区域中时自动禁用战斗统计, 战斗提醒和状态分享等功能",
    PvPmodeAnnouncement="PVP模式公告",
    PvPmodeAnnouncementDesc="在PVP模式中显示聊天栏公告",
    ChampionHelper	="勇士系统助手",
    ChampionHelperDesc	="在勇士系统界面记住技能和应用记住的勇士系统配置\n"..default..(BUI.Defaults.ChampionHelper and on or off),
    DisableHelpAnnounce ="禁用启动时公告",
    DisableHelpAnnounceDesc ="启用手柄和无障碍模式警示公告",
    GamepadHelpAnnouncement ="BUI不完全支持你目前所处的手柄模式",
    AccessibilityHelpAnnouncement ="你目前处于无障碍模式，这可能导致BUI和其他插件出错",
    ShortenThreshold	 ="缩写UI数值的阈值",
    ShortenThresholdDesc ="超过该数值时，改写为k的形式，比如10000 -> 10k",

    --Player frame
    PlayerFrame	="玩家框架",
    PlayerFrameDesc	="玩家框架风格",
    PlayerFrameWarn	="关闭时选择默认框架将立即重载界面!",
    DefaultPlayerFrames	="开启默认框架",
    DefaultPlayerFramesDesc	=default..(BUI.Defaults.DefaultPlayerFrames and on or off),
    DefaultPlayerFramesWarn	="开启此选项将立即重载界面!",
    RepositionFrames	="复位默认框架",
    RepositionFramesDesc	=default..(BUI.Defaults.RepositionFrames and on or off),
    RepositionFramesWarn	="禁用此选项将立即重载界面!",
    FramesTexture	="框架纹理",
    FramesTextureDesc	=default..BUI.Defaults.FramesTexture,
    FramesBorder	="框架边界",
    FramesBorderDesc	=default..BUI.Defaults.FramesBorder,
    PrimaryStat		="初始状态",
    PrimaryStatDesc	=default..BUI.Defaults.PrimaryStat,
    FrameHorisontal	="水平",
    FrameHorisontalDesc	="设置玩家框架水平或垂直.\n"..default..(BUI.Defaults.FrameHorisontal and "水平" or "垂直"),
    FramePercents	="展示百分比",
    FramePercentsDesc	=default..(BUI.Defaults.FramePercents and on or off),
    FrameShowMax	="展示最大生命值",
    FrameShowMaxDesc	="在玩家, 目标和组队框架中显示最大生命值\n"..default..(BUI.Defaults.FrameShowMax and on or off),
    DecimalValues	="小数值",
    DecimalValuesDesc	=default..(BUI.Defaults.DecimalValues and on or off),
    FrameWidth	="单位框架宽度",
    FrameWidthDesc	="设置单位框架的宽度.\n"..default..BUI.Defaults.FrameWidth,
    FrameHeight	="单位框架高度",
    FrameHeightDesc	="设置单位框架的高度.\n"..default..BUI.Defaults.FrameHeight,
    EnableNameplate	="展示玩家铭牌",
    EnableNameplateDesc	="在单位框架上显示你自己的角色铭牌\n"..default..(BUI.Defaults.EnableNameplate and on or off),
    FoodBuff	="食物增益功能",
    FoodBuffDesc	="根据食物加成改变玩家的属性条长度\n"..default..(BUI.Defaults.FoodBuff and on or off),
    EnableXPBar	="开启经验条",
    EnableXPBarDesc	="在玩家框架下展示你的经验/狼人计时器/攻城器生命/坐骑耐力条。\n"..default..(BUI.Defaults.EnableXPBar and on or off),
    ShowDots		="显示技能堆叠",
    ShowDotsDesc	="显示契约武器和百折不挠堆叠计数器。\n"..default..(BUI.Defaults.ShowDots and on or off),
    DodgeFatigue	="开启翻滚疲劳条",
    DodgeFatigueDesc	="翻滚之后显示疲劳进程条 (当疲劳持续时，另一个翻滚消耗双倍的耐力).\n"..default..(BUI.Defaults.DodgeFatigue and on or off),
    FramesFade	="自动隐藏",
    FramesFadeDesc	="当属性已满且玩家不在战斗状态时自动隐藏玩家属性\n"..default..(BUI.Defaults.FramesFade and on or off),
    Shield="伤害护盾",
    ShieldDesc="在资源条上显示伤害护盾",
    Trauma = "治疗吸收",
    TraumaDesc = "在资源条上显示治疗吸收",

    --Target frame
    TargetFrame	="额外目标框架",
    TargetFrameDesc	="使用自定义目标框架\n"..default..(BUI.Defaults.TargetFrame and on or off),
    DefaultTargetFrame	="默认目标框架",
    DefaultTargetFrameDesc	="继续显示默认 ESO 目标框架\n"..default..(BUI.Defaults.DefaultTargetFrame and on or off),
    DefaultTargetFrameText	="默认目标框架文本",
    DefaultTargetFrameTextDesc	="在默认目标框架上的额外信息",
    TargetFrameCenter = "居中目标框文本",
    TargetWidth	="目标框架宽度",
    TargetWidthDesc	="设置目标框架的宽度\n"..default..BUI.Defaults.TargetWidth,
    TargetHeight	="目标框架高度",
    TargetHeightDesc	="设置目标框架的高度\n"..default..BUI.Defaults.TargetHeight,
    TargetFramePercents	="显示百分比",
    TargetFramePercentsDesc	=default..(BUI.Defaults.TargetFramePercents and on or off),
    ExecuteThreshold	="处决阈值",
    ExecuteThresholdDesc	="为框架和文本警报设置所需的处决阈值生命百分比. 设置为零将禁用警报.\n"..default..BUI.Defaults.ExecuteThreshold,
    ExecuteSound	="处决声音",
    ExecuteSoundDesc	="处决阶段开始时播放'喀喇'声音\n"..default..(BUI.Defaults.ExecuteSound and on or off),
    BossFrame	="Boss框架",
    BossFrameDesc	=default..(BUI.Defaults.BossFrame and on or off),
    BossWidth	="Boss框架宽度",
    BossWidthDesc	="设置Boss框架的宽度\n"..default..BUI.Defaults.BossWidth,
    BossHeight	="Boss框架高度",
    BossHeightDesc	="设置Boss框架的高度\n"..default..BUI.Defaults.BossHeight,

    Attackers	="攻击者框架",
    AttackersDesc	="显示攻击你的敌人和其所造成的伤害。\n"..default..(BUI.Defaults.Attackers and on or off),
    AttackersWidth	="攻击者框架宽度",
    AttackersWidthDesc	="设置攻击者框架的宽度。\n"..default..BUI.Defaults.AttackersWidth,
    AttackersHeight	="攻击者框架高度",
    AttackersHeightDesc	="设置攻击者框架的高度。\n"..default..BUI.Defaults.AttackersHeight,

    --Fonts
    FrameNameFormat	="名称格式",
    FrameNameFormatValues	={"角色名","@账户名","角色名@账户名"},
    FrameFont1	="主要字体",
    FrameFont1Desc	="更改单位框架中使用的主要字体.\n"..default..BUI.TranslateFont(BUI.Defaults.FrameFont1),
    FrameFont2	="次要字体",
    FrameFont2Desc	="更改单位框架中使用的次要字体.\n"..default..BUI.TranslateFont(BUI.Defaults.FrameFont2),
    FrameFontSize	="框架字体大小",
    FrameFontSizeDesc	="更改单位框架中使用的字体的基本比例. \n"..default..BUI.Defaults.FrameFontSize,
    FrameOpacityIn	="战斗不透明度",
    FrameOpacityInDesc	="调整战斗中单位框架的不透明度. 较低的设置更透明.\n"..default..BUI.Defaults.FrameOpacityIn,
    FrameOpacityOut	="非战斗不透明度",
    FrameOpacityOutDesc	="调整战斗外单位框架的不透明度. 较低的设置更透明.\n"..default..BUI.Defaults.FrameOpacityOut,

    --Colors
    SelfColor	="自己颜色差异",
    SelfColorDesc	="在组队时使用不同颜色的玩家条\n"..default..(BUI.Defaults.SelfColor and on or off),
    CustomEdgeColor	="自定义主题颜色",
    CustomEdgeColorDesc	="所有界面框架的边缘颜色。\n"..default..BUI.TranslateColor(BUI.Defaults.CustomEdgeColor),
    AdvancedThemeColor	="高级主题颜色",
    AdvancedThemeColorDesc	="所有界面框架的HUD颜色和边缘颜色.\n"..default..BUI.TranslateColor(BUI.Defaults.AdvancedThemeColor),

    FrameHealthColor	="生命条颜色",
    FrameHealthColorDesc	="设置单位框架生命条颜色.\n"..default..BUI.TranslateColor(BUI.Defaults.FrameHealthColor),
    FrameMagickaColor	="魔力条颜色",
    FrameMagickaColorDesc	="设置玩家框架魔力条颜色\n"..default..BUI.TranslateColor(BUI.Defaults.FrameMagickaColor),
    FrameStaminaColor	="耐力条颜色",
    FrameStaminaColorDesc	="设置玩家框架耐力条颜色\n"..default..BUI.TranslateColor(BUI.Defaults.FrameStaminaColor),
    FrameShieldColor	="护盾条颜色",
    FrameShieldColorDesc	="设置玩家框架护盾条颜色\n"..default..BUI.TranslateColor(BUI.Defaults.FrameShieldColor),
    FrameTraumaColor    ="创伤条颜色",
    FrameTraumaColorDesc	="设置单位框架创伤条中显示的颜色.\n"..default..BUI.TranslateColor(BUI.Defaults.FrameTraumaColor),
    SameColors	="同样颜色",
    SameColorsDesc="将末端颜色设置为与首端颜色一样",

    ColorRoles	="根据角色改变框架颜色",
    ColorRolesDesc	="在组队和团队框架为每种战斗角色使用不同的颜色\n"..default..(BUI.Defaults.ColorRoles and on or off),
    FrameTankColor	="坦克角色颜色",
    FrameTankColorDesc	="在组队和团队框架中为坦克角色设置颜色.\n"..default..BUI.TranslateColor(BUI.Defaults.FrameTankColor),
    FrameHealerColor	="治疗角色颜色",
    FrameHealerColorDesc	="在组队和团队框架中为治疗角色设置颜色.\n"..default..BUI.TranslateColor(BUI.Defaults.FrameHealerColor),
    FrameDamageColor	="伤害角色颜色",
    FrameDamageColorDesc	="在组队和团队框架中为DPS角色设置颜色.\n"..default..BUI.TranslateColor(BUI.Defaults.FrameDamageColor),

    --Group frame
    RaidFrames	="开启组队框架",
    RaidFramesDesc	="使用自定义组队单位框架.\n"..default..(BUI.Defaults.RaidFrames and on or off),
    RaidCompact	="简洁模式",
    RaidCompactDesc	="(组队增益和DPS将被禁用)\n"..default..(BUI.Defaults.RaidCompact and on or off),
    GroupAnimation	="组队动画",
    GroupAnimationDesc	="开启 恢复/退化 状态动画\n"..default..(BUI.Defaults.GroupAnimation and on or off),
    GroupDeathSound	="队员死亡声音",

    RaidLevels	="显示等级",
    RaidLevelsDesc	=default..(BUI.Defaults.RaidLevels and on or off),
    RaidColumnSize	="团队框架列尺寸",
    RaidColumnSizeDesc	="组队框架中每列显示玩家数\n"..default..BUI.Defaults.RaidColumnSize,
    RaidWidth	="组队框架宽度",
    RaidWidthDesc	="为组队框架设置宽度.\n"..default..BUI.Defaults.RaidWidth,
    RaidHeight	="组队框架高度",
    RaidHeightDesc	="为组队框架设置高度.\n"..default..BUI.Defaults.RaidHeight,
    RaidFontSize	="组队框架字体尺寸",
    RaidFontSizeDesc	="更改组队框架中使用的字体的比例.\n"..default..BUI.Defaults.RaidFontSize,
    RaidStatValue	="资源数",
    
    --Advanced
    GroupElection	="高级就绪检查",
    GroupBuffs	="队伍Buff",
    GroupBuffsDesc	=default..(BUI.Defaults.GroupBuffs and on or off),
    StatusIcons	="队伍成员状态",
    StatusIconsDesc	="护甲耐久, 致命debuff, 号角图标.\n"..default..(BUI.Defaults.StatusIcons and on or off),
    SmallGroupScale	="小队尺寸",
    SmallGroupScaleDesc	="小队的额外框架比例\n"..default..BUI.Defaults.SmallGroupScale.."%",
    LargeRaidScale	="大团尺寸",
    LargeRaidScaleDesc	="为大团队降低比例\n"..default..BUI.Defaults.LargeRaidScale.."%",
    RaidSplit	="按小组划分团队",
    RaidSplitDesc	="定义小组内的玩家数量\n设为0以禁用",
    RaidSort		="团队分类",
    RaidSortDesc	="自动模式，包括为特定Boss进行高级分类。\n以主力量分类 (魔力, 耐力) 只在开启状态分享的队伍中生效。\n"..default..select(BUI.Defaults.RaidSort+1,"禁用","自动","以角色","以主力量","以等级"),
    ShieldGroup="伤害护盾",
    ShieldGroupDesc="在资源条上显示伤害护盾",
    TraumaGroup = "治疗吸收",
    TraumaGroupDesc = "在资源条上显示治疗吸收",
    --Stats share
    StatShare	="分享状态",
    StatShareDesc	="与队伍分享你的主要状态和终极.\n"..default..(BUI.Defaults.StatShare and on or off),
    StatShareUlt	="展示分享的终极",
    StatShareUltDesc	="特殊功能。团队队长使用(在团队框架每列之间保留空间)。\n"..default..select(BUI.Defaults.StatShareUlt,"全部","只有号角","禁用"),
    UltimateOrder	="终极顺序",
    UltimateOrderDesc	="显示号角和巨像顺序信息\n"..default..select(BUI.Defaults.UltimateOrder,"开启","自动","禁用"),
    --Group synergy
    GroupSynergy	="协同技能冷却",
    GroupSynergyDesc	="显示队伍成员激活协同技能冷却时间。\n"..default..select(BUI.Defaults.GroupSynergy,"全部","坦克","禁用"),
    GroupSynergyCount	="被显示的协同技能数量",
    GroupSynergyCountDesc	="被显示的协同技能数越大，团队框架每列之间的空间就越大。\n"..default..BUI.Defaults.GroupSynergyCount,
    --Group leader
    GroupLeaderHeader	="队长",
    MarkerLeader	="队长浮动标记",
    MarkerSize		="标记尺寸",

    --Curved Frames
    CurvedFrame	="弯曲框架风格",
    CurvedFrameDesc	=default..BUI.Defaults.CurvedFrame,
    CurvedDistance	="弯曲框架距离",
    CurvedDistanceDesc	=default..BUI.Defaults.CurvedDistance,
    CurvedDistanceWarn	="不能在菜单预览上展示",
    CurvedOffset	="弯曲框架垂直位移",
    CurvedOffsetDesc	=default..BUI.Defaults.CurvedOffset,
    CurvedHeight	="弯曲框架长度",
    CurvedHeightDesc	=default..BUI.Defaults.CurvedHeight,
    CurvedDepth	="弯曲框架深度和弯度",
    CurvedDepthDesc	=default..BUI.Defaults.CurvedDepth*100 ,
    CurvedStatValues	="展示弯曲框架状态值",
    CurvedStatValuesDesc	=default..(BUI.Defaults.CurvedStatValues and on or off),
    CurvedHitAnimation	="致命一击动画",
    CurvedHitAnimationDesc	=default..(BUI.Defaults.CurvedHitAnimation and on or off),
    CurvedShift	="属性位置切换",
    CurvedShiftDesc	="战斗结束后将属性切换到另一边。\n"..default..(BUI.Defaults.CurvedShift and on or off),
    CurvedShiftAnimation	="切换动画",
    CurvedShiftAnimationDesc	=default..(BUI.Defaults.CurvedShiftAnimation and on or off),

    --Damage Report Menu
    StatMiniHeader	="迷你仪表",
    StatsMiniMeter	="展示迷你仪表",
    StatsMiniMeterDesc	=default..(BUI.Defaults.StatsMiniMeter and on or off),
    MiniMeterAplha	="迷你仪表初值",
    MiniMeterAplhaDesc	=default..BUI.Defaults.MiniMeterAplha*100 ,
    StatsMiniHealing	="展示迷你仪表hps",
    StatsMiniHealingDesc	=default..(BUI.Defaults.StatsMiniHealing and on or off),
    StatsMiniGroupDps	="展示迷你仪表队伍dps",
    StatsMiniGroupDpsDesc	=default..(BUI.Defaults.StatsMiniGroupDps and on or off),
    StatsMiniSpeed	="展示迷你仪表循环速度",
    StatsMiniSpeedDesc	=default..(BUI.Defaults.StatsMiniSpeed and on or off),

    StatsUpdateDPS	="DPS分享",
    StatsUpdateDPSDesc	=default..(BUI.Defaults.StatsUpdateDPS and on or off),
    StatsGroupDPS	="成员面板上的DPS",
    StatsGroupDPSDesc	="在小组成员面板贴出dps(简洁模式下禁用)\n"..default..(BUI.Defaults.StatsGroupDPS and on or off),
    StatsGroupDPSframe	="在额外框架上的DPS",
    StatsGroupDPSframeDesc	="显示小组成员DPS\n"..default..(BUI.Defaults.StatsGroupDPSframe and on or off),
    StatsSplitElements	="标注元素类型",
    StatsSplitElementsDesc	="为轻击、重击、力量冲击、伊拉姆布里斯等标注元素类型\n"..default..(BUI.Defaults.StatsSplitElements and on or off),
    StatsBuffs	="玩家和目标增益报告",
    StatsBuffsDesc	="在伤害报告窗口开启玩家和目标的增益/减益部分\n"..default..(BUI.Defaults.StatsBuffs and on or off),

    Log	="战斗日志",
    LogDesc	="用于复盘战斗，根据已启用的统计和提醒模块功能进行记录。需要在键位设置中绑定一个按键用于打开报告界面"..default..(BUI.Defaults.Log and on or off),

    --Buffs
    PlayerBuffs	="玩家增益",
    PlayerBuffsDesc	=default..(BUI.Defaults.PlayerBuffs and on or off),
    BuffsOtherHide	="隐藏来自其他玩家的增益",
    BuffsOtherHideDesc	="除掉某些重要增益例如吸取, 艾尔克许, etc.\n"..default..(BUI.Defaults.BuffsOtherHide and on or off),
    BuffsImportant	="用不同大小显示重要效果",
    BuffsImportantDesc	="号角, 吸取, 高级力量, 杀手, 失衡, 套装效果例如艾尔克许, 月舞者, BSW, etc. \n"..default..(BUI.Defaults.BuffsImportant and on or off),
    MinimumDuration	="最小增益持续时长",
    MinimumDurationDesc	=default..BUI.Defaults.MinimumDuration,
    PlayerBuffsAlign	="玩家增益排列",
    PlayerBuffsAlignDesc	=default..AlignValues[BUI.Defaults.PlayerBuffsAlign],
    PlayerBuffSize	="玩家增益图标尺寸",
    PlayerBuffSizeDesc	=default..BUI.Defaults.PlayerBuffSize,

    TargetBuffs	="目标增益",
    TargetBuffsDesc	=default..(BUI.Defaults.TargetBuffs and on or off),
    TargetBuffSize	="目标增益图标尺寸",
    TargetBuffSizeDesc	=default..BUI.Defaults.TargetBuffSize,
    TargetBuffsAlign	="目标增益排列",
    TargetBuffsAlignDesc	=default..AlignValues[BUI.Defaults.TargetBuffsAlign],

    BuffsPassives	="被动",
    BuffsPassivesDesc	=default..(BUI.Defaults.BuffsPassives),
    PassiveProgress	="被动进程条",
    PassiveProgressDesc	=default..(BUI.Defaults.PassiveProgress and on or off),
    PassivePWidth	="进程条宽度",
    PassivePWidthDesc	=default..BUI.Defaults.PassivePWidth,
    PassivePSide	="进程条方位",
    PassivePSideDesc	=default..BUI.Defaults.PassivePSide,
    PassiveBuffSize	="被动增益图标大小",
    PassiveBuffSizeDesc	=default..BUI.Defaults.PassiveBuffSize,
    PassiveOakFilter="隐藏橡树之魂增益",
    PassiveOakFilterDesc=default..(BUI.Defaults.PassiveOakFilter and on or off),

    BlackListHeader	="增益黑名单",
    EnableBlackList	="为增益应用黑名单",
    EnableBlackListDesc	=default..(BUI.Defaults.EnableBlackList and on or off),
    BlackListAdd	="加入黑名单",
    BlackListAddDesc	="输入增益名字（对于所有具有特定名称的增益，区分大小写）或增益id来加入黑名单. 或者直接在增益面板上对其点击右键.",
    BlackListDel	="剔出黑名单",
    BlackListDelDesc	="选择增益来把他剔出黑名单",

    CustomBuffsHeader	="自定义增益面板",
    EnableCustomBuffs	="开启自定义增益面板",
    EnableCustomBuffsDesc	=default..(BUI.Defaults.EnableCustomBuffs and on or off),
    CustomBuffsAdd	="添加到自定义增益",
    CustomBuffsAddDesc	="输入名字或增益id来加入自定义. 或者直接在增益面板上对其点击左键.",
    CustomBuffsDel	="从自定义增益删除",
    CustomBuffsDelDesc	="选择增益来把他剔出自定义增益",
    CustomBuffsDirection	="自定义增益方向",
    CustomBuffsDirectionDesc	=default..BUI.Defaults.CustomBuffsDirection,
    CustomBuffsProgress	="自定义增益进程条",
    CustomBuffsProgressDesc	="只在垂直方向可用.\n"..default..(BUI.Defaults.CustomBuffsProgress and on or off),
    CustomBuffsPWidth	="进程条宽度",
    CustomBuffsPWidthDesc	=default..BUI.Defaults.CustomBuffsPWidth,
    CustomBuffsPSide	="进程条方位",
    CustomBuffsPSideDesc	=default..BUI.Defaults.CustomBuffsPSide,
    CustomBuffSize	="自定义增益图标尺寸",
    CustomBuffSizeDesc	=default..BUI.Defaults.CustomBuffSize,

    SynergyCdHeader	="协同冷却面板",
    EnableSynergyCd	="开启协同冷却面板",
    EnableSynergyCdDesc	=default..(BUI.Defaults.EnableSynergyCd and on or off),
    SynergyCdDirection	="方向",
    SynergyCdDirectionDesc	=default..BUI.Defaults.SynergyCdDirection,
    SynergyCdProgress	="进程条",
    SynergyCdProgressDesc	="只在垂直方向可用。\n"..default..(BUI.Defaults.SynergyCdProgress and on or off),
    SynergyCdPWidth	="进程条宽度",
    SynergyCdPWidthDesc	=default..BUI.Defaults.SynergyCdPWidth,
    SynergyCdPSide	="进程条方位",
    SynergyCdPSideDesc	=default..BUI.Defaults.SynergyCdPSide,
    SynergyCdSize	="图标大小",
    SynergyCdSizeDesc	=default..BUI.Defaults.SynergyCdSize,

    --Widgets
    WidgetsHeader	="小工具",
    EnableWidgets	="开启小工具",
    EnableWidgetsDesc	=default..(BUI.Defaults.EnableWidgets and on or off),
    WidgetsSize	="小工具尺寸",
    WidgetsSizeDesc	=default..BUI.Defaults.WidgetsSize,
    WidgetsAdd	="添加小工具",
    WidgetsAddDesc	="输入名字或增益id来加入小工具. 或者直接在增益面板上对其点击中键.",
    WidgetsProgress	="进程条",
    WidgetsPWidth	="进程条宽度",
    WidgetsPWidthDesc	=default..BUI.Defaults.WidgetsPWidth,
    WidgetsMultiTarget	="多目标",
    WidgetsSelfEffects	="只开启玩家效果",
    WidgetsAlwaysShow	="一直显示",
    WidgetsCombine	="额外效果",
    WidgetsCombineDesc	="此处你可添加额外效果的名字或ID，它将显示为额外进程条。\n留白则禁用此项。",
    WidgetPotion	="药水小工具",
    WidgetPotionDesc	="当资源不足且药剂准备好时显示药剂图标\n"..default..(BUI.Defaults.WidgetPotion and on or off),
    WidgetSound1	="激活声音",
    WidgetSound1Desc	="是否播放激活和失效声音选项，可以在小工具设置中为不同的小工具分别设置是否开启。",
    WidgetSound2	="失效声音",
    WidgetSound2Desc	="是否播放激活和失效声音选项，可以在小工具设置中为不同的小工具分别设置是否开启。",
    WidgetsSoundDesc	="",
    WidgetsPSide	="进程条方位",
    WidgetsCooldownDesc	="在这里，您可以更改自定义小工具冷却 (毫秒).\n保留空白以使用默认值.",
    WidgetsManage	="管理小工具",
    WidgetsReset	="重置位置",
    WidgetsAbility	="技能",
    WidgetsAbilityDesc	="必须开启技能计时器",
    WidgetsBuff		="最近增益",
    WidgetsBuffDesc	="必须开启伤害统计增益",
    WidgetsCustom	="自定义",

    --Actions
    Actions	="展示技能计时器",
    ActionsDesc	=default..(BUI.Defaults.Actions and on or off),
    ActionsPrecise	="精确模式",
    ActionsPreciseDesc	="当技能生效时，精确模式计时器将启动\n"..default..(BUI.Defaults.ActionsPrecise and on or off),
    ProcAnimation	="技能激活动画",
    ProcAnimationDesc	='碎裂水晶，刺客之愿，自爆枯骨等技能的的"准备好了" 动画  '..default..(BUI.Defaults.ProcAnimation and on or off),
    ProcSound	="技能激活声音",
    UseSwapPanel	="显示切换面板",
    UseSwapPanelDesc	=default..(BUI.Defaults.UseSwapPanel and on or off),
    HideSwapPanel	="自动隐藏切换面板",
    HideSwapPanelDesc	="闲置技能将被隐藏\n"..default..(BUI.Defaults.UseSwapPanel and on or off),
    FullSwapPanel	="显示完整切换面板",
    FullSwapPanelDesc	="显示整个切换面板\n"..default..(BUI.Defaults.UseSwapPanel and on or off),
    ExpiresAnimation	="到期动画",
    ExpiresAnimationDesc	=default..(BUI.Defaults.ExpiresAnimation and on or off),
    ActionsFontSize	="字体尺寸",
    ActionsFontSizeDesc	=default..BUI.Defaults.ActionsFontSize,

    --Automation
    AutoConfirm	="自动确认",
    UndauntedDaily	="日常",
    UndauntedQuest	="任务",
    UndauntedDone	="完成",
    AutomationHeader	="自动",
    BlockingsHeader	="阻挡",
    ImprovementsHeader	="提升",
    Teleporter	="传送点",
    TeleporterDesc	="添加到位置列表选项，以在选定区域内免费传送.(必须安装聊天标签选择器)",
    DeleteMail	="自动删除邮件",
    DeleteMailDesc	="删除没有附件的邮件时跳过确认对话框.",
    JumpToLeader	="跳到队长",
    JumpToLeaderDesc	="禁用跳到队长的邀请.",
    GroupLeave	="离开组队",
    GroupLeaveDesc	="离开组队时禁用确认对话框.",
    Books	="自动关闭书本",
    BooksDesc	="如果你想读这本书，就再用一次.",
    LargeGroupInvite	="大团队邀请",
    LargeGroupInviteDesc	="禁用大团队邀请警告.",
    LargeGroupAnnoucement	="大团队公告",
    LargeGroupAnnoucementDesc	="禁用聊天中的大/小团队公告.",
    FriendStatus	="好友状态",
    FriendStatusDesc	="禁用好友 \"登入登出\" 聊天信息.",
    FastTravel	="快速旅行",
    FastTravelDesc	="在使用路点神龛时禁用确认对话框.",
    InitialDialog	="NPC初始对话",
    InitialDialogDesc	="银行, 商店, 介绍任务",
    RepeatableQuests	="可重复任务处理器",
    RepeatableQuestsDesc	="自动 确认/完成 可重复任对话框。",
    CovetousCountess	="盗贼公会: 贪婪的伯爵夫人",
    CovetousCountessDesc	="无 \"贪婪的伯爵夫人\" 合约会被跳过. 需要再次按下交互按钮.",
    DarkBrotherhoodSpree	="黑暗兄弟会: 杀戮盛宴契约",
    DarkBrotherhoodSpreeDesc	="无杀戮盛宴契约会被跳过. 需要再次按下交互按钮.",
    --FeedSynergy	="进食协同",
    --FeedSynergyDesc	="禁用吸血鬼的\"进食\"协同技能来使用 \"哀伤匕首\".",
    AdvancedSynergy	="高级协同",
    AdvancedSynergyDesc	="为坦克和治疗者禁用\"充能闪电\"。\n云栖城: 自动禁用可能阻碍进入传送门或掉落“移除尖啸冰霜”的协同，如果它们恰好出现在具有更高优先级的协同之前。\n"..default..(BUI.Defaults.AdvancedSynergy and on or off),
    BlockAnnouncement	="拦截公告",
    BlockAnnouncementDesc	="拦截登录时系统公告",
    ContainerHandler	="容器处理器",
    ContainerHandlerDesc	="添加物品栏选项来自动打开容器或切片鱼肉.",
    StealthWield	="在潜行状态下显示武器",
    StealthWieldDesc	="",
    LootStolen	="潜行时自动偷窃物品",
    LootStolenDesc	="",
    UndauntedPledges	="活动查找器：无畏者誓约",
    UndauntedPledgesDesc	="在活动查找器中添加一个按钮来标记与当前无畏者誓约相关的地下城\n添加地下城成就信息",
    DungeonQuests	="活动查找器：地下城技能点任务",
    DungeonQuestsDesc	="在活动查找器中添加一个按钮来标记未完成的地下城技能点任务\n在成就信息中添加任务图标",
    CollapseNormalDungeon	="折叠普通地下城",
    CollapseNormalDungeonDesc	="在地牢查找器窗口中折叠普通地牢。\n仅在启用无畏誓言时可用。",
    ConfirmLocked	="自动确认被锁定的物品",
    ConfirmLockedDesc	="转化/提升/附魔 被锁定的物品时，自动添加 \"确认\" 文本到确认对话框中。",
    PlayerToPlayer	="玩家对玩家提示",
    PlayerToPlayerDesc	="移除踢出队伍选项 (这是为了消除在试图复活玩家时不小心将玩家踢出队伍的可能性)",
    BuiltInGlobalCooldown="启用内置全局冷却时间",
    BuiltInGlobalCooldownDesc="在登录时设置内置的全局冷却时间。",
    AutoDismissPet="自动解雇非战斗宠物（试炼）.",
    AutoDismissPetDesc="进入试炼时解雇非战斗宠物.",
    HousePins	="隐藏地图住房图标",
    HousePinsDesc	="仅隐藏 \"住房\" 图标。标签不会被移除。",
    ActFinderButton	="勾选当前誓约",

    Meters_Header	="计量仪",
    Meter_Speed	="速度",
    Meter_SpeedDesc	="显示玩家移动速度。",
    Meter_Power	="力量",
    Meter_PowerDesc	="显示玩家法术或武器伤害。",
    Meter_Crit	="暴击",
    Meter_CritDesc	="显示玩家法术或武器暴击几率。",
    Meter_Exp	="经验",
    Meter_ExpDesc	="显示玩家经验。",
    Meter_DPS	="DPS",
    Meter_DPSDesc	="显示当前和最后的DPS值。",
    Meter_Criminal	="犯罪",
    Meter_CriminalDesc	="显示赏金和热度仪。",
    Meter_Scale	="计量仪尺寸",

    Markers_Header="标记",
    Markers_IconDuration="以秒为单位显示图标的持续时间",
    Markers_Dungeons="在地下城中显示标记",
    Markers_Trials="在试炼中显示标记",
    Markers_Message="在聊天框中显示找到宝箱的消息",
    Markers_Icon="在找到宝箱时显示图标",
    Markers_HeavySack="发现重袋时也会显示标记",
    
    Daily_NPC_Glirion="红胡子格利里恩",
    Daily_NPC_Maj="玛吉·阿尔拉加斯",
    Daily_NPC_Urgarlag="乌尔加拉格·酋长克星",

    STATISTICS_Incoming="承伤",
    STATISTICS_Group="小队",
    STATISTICS_GroupMember="小队成员",
    STATISTICS_Item="装备",
    STATISTICS_Trait="特性",
    STATISTICS_Enchant="附魔",
    STATISTICS_Recovery="恢复",
    STATISTICS_PEN_AVG_MAX="穿透 平均/最大",
    STATISTICS_Fire="火焰",
    STATISTICS_Shock="电击",
    STATISTICS_Cold="寒霜",
    STATISTICS_Magic="魔法",
    STATISTICS_Physical="物理",
    STATISTICS_Poison="毒素",
    STATISTICS_Disease="疾病",
    STATISTICS_Bleed="流血",
    STATISTICS_Direct_Dmg="直接伤害",
    STATISTICS_Weapon_Attack="武器攻击/技能",
    STATISTICS_Rotation_Speed="转速",
    STATISTICS_Weapon="武器",
    STATISTICS_Spell="法术",
    STATISTICS_Uptimes="时间轴",
    STATISTICS_Uptimes_For="战斗时长: ",
    STATISTICS_Swap="切手",
    STATISTICS_Up="覆盖",
    STATISTICS_Death="死亡",
    STATISTICS_Report="报告",
    STATISTICS_Report_Deleted="已发现",
    STATISTICS_Report_Saved="已保存",
    STATISTICS_Group_DMG_Results="团伤报告",
    STATISTICS_In="在",
    STATISTICS_TotalDamage="总伤",
    STATISTICS_Over="在",
    STATISTICS_Every="每",

    SETTINGS_ReloadingUI="重新加载UI",

    ACTIVITYFINDER_DailyPledges = "无畏者日常",

    AUTOMATION_Left="左键",
    AUTOMATION_Stop="停止",
    AUTOMATION_SETTINGS_MAP_PIN_All="所有",
    AUTOMATION_SETTINGS_MAP_PIN_Owned="已拥有",
    AUTOMATION_SETTINGS_MAP_PIN_Unowned="未拥有",
    AUTOMATION_SETTINGS_MAP_PIN_Disabled="禁用",
    AUTOMATION_Global_Cooldown="设置全局冷却",
    AUTOMATION_Quest_Low_Reward="低收益任务已被跳过",
  }
  
  --Special Setting
  BB.SetMenuItemPatch("Post DPS", "发布DPS统计")
  BB.SetMenuItemPatch("Post death count", "发布死亡计数")
  BB.SetMenuItemPatch("Clear death count", "清空死亡计数")
  BB.SetMenuItemPatch("Save group list", "保存队伍列表")
  BB.SetMenuItemPatch("Post group list", "发布队伍列表")
  BB.SetMenuItemPatch("Regroup", "重组")
  BB.SetMenuItemPatch("Refresh frame", "刷新框架")
  
  local icons = {
    zo_iconFormat("/EsoUI/Art/Compass/groupLeader.dds",32,32),
    zo_iconFormat("/EsoUI/Art/MapPins/UI-WorldMapGroupPip.dds",32,32),
    zo_iconFormat("/esoui/art/icons/poi/poi_areaofinterest_complete.dds",32,32),
    zo_iconFormat("/esoui/art/icons/poi/poi_wayshrine_complete.dds",32,32),
    zo_iconFormat("/esoui/art/compass/quest_icon_assisted.dds",32,32),
  }
  
  local replaceLists = {
    ["name"] = {
      [icons[1].." Group leader"]   = icons[1].." 小队成员",
      [icons[2].." Group member"]   = icons[2].." 队长",
      [icons[3].." POI complete"]   = icons[3].." 已知标记性地点",
      [icons[4].." Wayshrine"]      = icons[4].." 路点神龛",
      [icons[5].." Quest complete"] = icons[5].." 已完成任务",
    },
  }
  
  BB.SetMenuReplace("BUI_MenuMinimap", replaceLists)
  
return true end