local BB = MABabel
--[[ 
BB.AddonList[""] = function() if not  then return false end
return true end

do if not BB.SV.BanList[""] then
end end
BB.AddonList[""] = function() if not  then return false end
return true end
]]

do if not BB.SV.BanList["FurnitureCatalogue"] then
  --en.lua
  local strings = {
    SI_FURC_ADD_FAVE = " 添加收藏夹",
    SI_FURC_DATAMINED_UNCLEAR = "该物品已在游戏中出现，但尚不清楚如何获取",
    
    SI_FURC_DB = "黑暗兄弟会，暗影供应者 ",
    SI_FURC_DB_EQUIP = "(装备选项)",
    SI_FURC_DB_POISON = "(毒药选项)",
    SI_FURC_DB_STEALTH = "(不引人注目选项)",
    
    SI_FURC_DEBUG_CHARSCANCOMPLETE = "Furniture Catalogue: 角色检索完成...",
    SI_FURC_DIALOGUE_RESET_DB_BODY = "这将从头开始重新创建 Furniture Catalogue 数据库",
    SI_FURC_DIALOGUE_RESET_DB_HEADER = "真的要重新创建家具数据库吗？",
    SI_FURC_DUNG = "地下城",
    
    SI_FURC_EVENT = "活动",
    SI_FURC_EVENT_ANNIVERSARY = "周年庆典",
    SI_FURC_EVENT_BLACKWOOD = "黑木的赏金",
    SI_FURC_EVENT_ELSWEYR = "龙临盛季",
    SI_FURC_EVENT_HOLLOWJACK = "万圣杰克",
    SI_FURC_EVENT_IC = "帝都庆典",
    SI_FURC_EVENT_JESTER = "小丑节",
    SI_FURC_EVENT_MAYHEM = "怀特斯垂克大乱斗",
    SI_FURC_EVENT_NEWLIFE = "新生节",
    SI_FURC_EVENT_UNDAUNTED = "无畏者庆典",
    SI_FURC_EVENT_WITCHES = "女巫庆典",
    SI_FURC_EVENT_ZENITHAR = "泽尼萨尔的热忱",
    
    SI_FURC_FILTER_CHAR_OFF = "角色筛选器: 关闭",
    SI_FURC_FILTER_CHAR_OFF_TT = "禁用该筛选器",
    
    SI_FURC_FILTER_CROWN_HIDE_TT = "已显示王冠商店物品，点击隐藏",
    SI_FURC_FILTER_RUMOUR_HIDE_TT = "已显示谣言物品，点击隐藏",
    
    SI_FURC_FILTER_SRC_NONE = "来源筛选器: 关闭",
    SI_FURC_FILTER_SRC_NONE_TT = "禁用该筛选器",
    SI_FURC_FILTER_SRC_CRAFTING = "可制作: 全部",
    SI_FURC_FILTER_SRC_CRAFTING_TT = "显示所有可制作物品",
    SI_FURC_FILTER_SRC_CRAFTING_KNOWN = "可制作: 已知",
    SI_FURC_FILTER_SRC_CRAFTING_KNOWN_TT = "仅显示已知的可制作物品",
    SI_FURC_FILTER_SRC_CRAFTING_UNKNOWN = "可制作: 未知",
    SI_FURC_FILTER_SRC_CRAFTING_UNKNOWN_TT = "仅显示未知的可制作物品",
    SI_FURC_FILTER_SRC_CROWN = "王冠商店",
    SI_FURC_FILTER_SRC_CROWN_TT = "显示仅可从王冠商店获取的物品",
    SI_FURC_FILTER_SRC_FAVE = "收藏夹",
    SI_FURC_FILTER_SRC_FAVE_TT = "显示你收藏的物品",
    SI_FURC_FILTER_SRC_LUX = "豪华物品",
    SI_FURC_FILTER_SRC_LUX_TT = "冷港NPC扎尼尔·瑟兰定期出售的物品",
    SI_FURC_FILTER_SRC_OTHER = "其他",
    SI_FURC_FILTER_SRC_OTHER_TT = "显示其他途径获取的物品",
    SI_FURC_FILTER_SRC_RUMOUR = "谣言物品",
    SI_FURC_FILTER_SRC_RUMOUR_TT = "由解包发现的物品和配方，但尚未被确认存在",
    SI_FURC_FILTER_SRC_SOLD_AP = "可购买 (AP)",
    SI_FURC_FILTER_SRC_SOLD_AP_TT = "可通过联盟点数购买的物品",
    SI_FURC_FILTER_SRC_SOLD_GOLD = "可购买 (金币)",
    SI_FURC_FILTER_SRC_SOLD_GOLD_TT = "显示无法制作的物品",
    SI_FURC_FILTER_SRC_SOLD_WRIT = "可购买 (任务令卷)",
    SI_FURC_FILTER_SRC_SOLD_WRIT_TT = "可通过任务令卷(大师卷)购买的物品",
    
    SI_FURC_FILTER_VERSION_OFF = "游戏版本筛选器: 关闭",
    SI_FURC_FILTER_VERSION_OFF_TT = "禁用该筛选器",
    SI_FURC_FILTER_VERSION_BASED = "基础游戏补丁",
    SI_FURC_FILTER_VERSION_BASED_TT = "当你失去名字的时候",
    SI_FURC_FILTER_VERSION_HS = "家园",
    SI_FURC_FILTER_VERSION_HS_TT = "家园更新中发布的物品",
    SI_FURC_FILTER_VERSION_M = "晨风",
    SI_FURC_FILTER_VERSION_M_TT = "你个外地人！",
    SI_FURC_FILTER_VERSION_R = "瑞驰号角",
    SI_FURC_FILTER_VERSION_R_TT = "因为我们所需要的只是更多的瑞驰人",
    SI_FURC_FILTER_VERSION_CC = "发条城",
    SI_FURC_FILTER_VERSION_CC_TT = "飞轮转动的地方，黄铜很漂亮",
    SI_FURC_FILTER_VERSION_DRAGON = "龙骨",
    SI_FURC_FILTER_VERSION_DRAGON_TT = "如果你从西斯·德伦那里得到这个，那么...",
    SI_FURC_FILTER_VERSION_ALTMER = "夏暮岛",
    SI_FURC_FILTER_VERSION_ALTMER_TT = "还是觉得丹莫不好？",
    SI_FURC_FILTER_VERSION_WEREWOLF = "猎狼人",
    SI_FURC_FILTER_VERSION_WEREWOLF_TT = "在狩猎场, 狼人追杀你",
    SI_FURC_FILTER_VERSION_SLAVES = "幽暗沼泽",
    SI_FURC_FILTER_VERSION_SLAVES_TT = "亚龙人的孩子在学校学什么？希思特树",
    SI_FURC_FILTER_VERSION_WOTL = "怒灵石",
    SI_FURC_FILTER_VERSION_WOTL_TT = "怒灵石!",
    SI_FURC_FILTER_VERSION_KITTY = "艾斯维尔",
    SI_FURC_FILTER_VERSION_KITTY_TT = "虎人有很多家具，如果你有钱的话!",
    SI_FURC_FILTER_VERSION_SCALES = "断鳞者",
    SI_FURC_FILTER_VERSION_SCALES_TT = "Fus Ro Dah?",
    SI_FURC_FILTER_VERSION_DRAGON2 = "龙之要塞",
    SI_FURC_FILTER_VERSION_DRAGON2_TT = "现在我们有更多龙了",
    SI_FURC_FILTER_VERSION_HARROW = "血疫风暴",
    SI_FURC_FILTER_VERSION_HARROW_TT = "气候变化是真实的",
    SI_FURC_FILTER_VERSION_SKYRIM = "灰色沼泽",
    SI_FURC_FILTER_VERSION_SKYRIM_TT = "他们*又*卖了一次天际!",
    SI_FURC_FILTER_VERSION_STONET = "石与荆棘",
    SI_FURC_FILTER_VERSION_STONET_TT = "那不是真的石头",
    SI_FURC_FILTER_VERSION_MARKAT = "马卡斯城",
    SI_FURC_FILTER_VERSION_MARKAT_TT = "使用矮人管道",
    SI_FURC_FILTER_VERSION_FLAMES = "野心之火",
    SI_FURC_FILTER_VERSION_FLAMES_TT = "轻度易燃",
    SI_FURC_FILTER_VERSION_BLACKW = "黑木",
    SI_FURC_FILTER_VERSION_BLACKW_TT = "梅鲁涅斯永远学不会",
    SI_FURC_FILTER_VERSION_DEADL = "死地",
    SI_FURC_FILTER_VERSION_DEADL_TT = "这是什么地方，有闪闪发光的肉？",
    SI_FURC_FILTER_VERSION_TIDES = "潮起",
    SI_FURC_FILTER_VERSION_TIDES_TT = "红卫. 结构. 家具 (有点儿?)",
    SI_FURC_FILTER_VERSION_BRETON = "高岛",
    SI_FURC_FILTER_VERSION_BRETON_TT = "这里遍地海盗",
    SI_FURC_FILTER_VERSION_DEPTHS = "失落深渊",
    SI_FURC_FILTER_VERSION_DEPTHS_TT = "潘格瑞到底是什么?",
    SI_FURC_FILTER_VERSION_DRUID = "焱歌",
    SI_FURC_FILTER_VERSION_DRUID_TT = "记住什么时候我们可以阻止?",
    SI_FURC_FILTER_VERSION_SCRIBE = "命运书写师",
    SI_FURC_FILTER_VERSION_SCRIBE_TT = "书籍和事物",
    SI_FURC_FILTER_VERSION_NECROM = "死灵之地",
    SI_FURC_FILTER_VERSION_NECROM_TT = "这么多触手",
    SI_FURC_FILTER_VERSION_ENDLESS = "泰尔瓦尼的秘密",
    SI_FURC_FILTER_VERSION_ENDLESS_TT = "现在有了无限的触手",
    SI_FURC_FILTER_VERSION_SCIONS = "伊瑟利娅的后裔",
    SI_FURC_FILTER_VERSION_SCIONS_TT = "是的，怀特先生，后裔！",
    SI_FURC_FILTER_VERSION_WEALD = "黄金大道",
    SI_FURC_FILTER_VERSION_WEALD_TT = "我们忘记了...谁？",
    SI_FURC_FILTER_VERSION_BASE43 = "U43更新",
    SI_FURC_FILTER_VERSION_BASE43_TT = "住宅巡览",
    SI_FURC_FILTER_VERSION_BASE44 = "U44更新",
    SI_FURC_FILTER_VERSION_BASE44_TT = "双方斗争",
    SI_FURC_FILTER_VERSION_FALLBAN = "落旗",
    SI_FURC_FILTER_VERSION_FALLBAN_TT = "新的地下城和视觉效果更新",
    
    SI_FURC_GRAMMAR_CONJ_OR = "或",
    SI_FURC_GRAMMAR_PREP_LOC_DEFAULT = "在", -- used for locations "in Betnikh"
    SI_FURC_GRAMMAR_PREP_SRC_DEFAULT = "从", -- used for sources "from traders"
    
    SI_FURC_GUILD_FIGHTERS = "斗士公会",
    SI_FURC_GUILD_FIGHTERS_STEWARD = "公会管家",
    SI_FURC_GUILD_MAGES = "法师公会",
    SI_FURC_GUILD_MAGES_MYSTIC = "神秘商人^n",
    SI_FURC_GUILD_MAGES_MYSTIC_COLL = "神秘商人处成套购买",
    SI_FURC_GUILD_PSIJIC_NALIRSEWEN = "纳利瑟文^F",
    SI_FURC_GUILD_THIEVES_MERCH = "罪犯避难所，商人",
    SI_FURC_GUILD_UNDAUNTED_QM = "军需官",
    
    SI_FURC_HOUSE = "来自带有家具的 <<1>> 的购买",
    SI_FURC_ITEMPACK_ALCHEMIST = "疯狂炼金术士",
    SI_FURC_ITEMPACK_AMBITIONS = "魔族野心领主",
    SI_FURC_ITEMPACK_AQUATIC = "水上奇观",
    SI_FURC_ITEMPACK_ASTULA = "莎德阿斯图拉学者",
    SI_FURC_ITEMPACK_AYLEID = "野精灵",
    SI_FURC_ITEMPACK_AZURA = "阿祖拉",
    SI_FURC_ITEMPACK_COLDHARBOUR = "冷港奥术厅",
    SI_FURC_ITEMPACK_COVEN = "女巫团",
    SI_FURC_ITEMPACK_CRAGKNICKS = "荒崖多元文化内饰",
    SI_FURC_ITEMPACK_CURIOSITIES = "异典奇珍",
    SI_FURC_ITEMPACK_DEEPMIRE = "深沼探险",
    SI_FURC_ITEMPACK_DIBELLA = "迪贝拉花园",
    SI_FURC_ITEMPACK_DWEMER = "矮人管道",
    SI_FURC_ITEMPACK_FARGRAVE = "法格雷夫集市",
    SI_FURC_ITEMPACK_FORGE = "锻造大君的鬼斧神工",
    SI_FURC_ITEMPACK_HEART = "恋心节回馈",
    SI_FURC_ITEMPACK_HUBTREASURE = "胡巴拉贾德最后的宝藏",
    SI_FURC_ITEMPACK_KHAJIIT = "虎人生活",
    SI_FURC_ITEMPACK_MALACATH = "玛拉卡斯的精选",
    SI_FURC_ITEMPACK_MAORMER = "海精灵搜查队",
    SI_FURC_ITEMPACK_MEPHALA = "梅法拉崇拜者陷阱",
    SI_FURC_ITEMPACK_MERMAID = "蒸气浴中的宁静",
    SI_FURC_ITEMPACK_MOLAG = "莫拉格·巴尔",
    SI_FURC_ITEMPACK_MOONBISHOP = "月之主教圣所",
    SI_FURC_ITEMPACK_NEWLIFE2018 = "新生节",
    SI_FURC_ITEMPACK_OASIS = "月之祝福绿洲",
    SI_FURC_ITEMPACK_SOTHA = "机械神域",
    SI_FURC_ITEMPACK_SWAMP = "影与石",
    SI_FURC_ITEMPACK_TYRANTS = "精灵纪元的暴君",
    SI_FURC_ITEMPACK_VAMPIRE = "吸血鬼祭酒",
    SI_FURC_ITEMPACK_VIVEC = "维威克领主",
    SI_FURC_ITEMPACK_WINDOWS = "诸神窗户",
    SI_FURC_ITEMPACK_ZENI = "泽尼萨尔大教堂",
    SI_FURC_LABEL_ENTRIES = " 条目 -",
    
    SI_FURC_LOC_ANY = "任意地点^X",
    SI_FURC_LOC_ANY_CAPITAL = "任意联盟首都",
    SI_FURC_LOC_ANY_CITY = "任意城市",
    SI_FURC_LOC_LILANDRIL = "利兰德里尔",
    SI_FURC_LOC_MURKMIRE_LIL = "利尔莫斯",
    SI_FURC_LOC_PLACE_ORSINIUM = "奥辛纽姆",
    SI_FURC_LOC_REACH_MARKARTH_MM = "马卡斯商业区",
    SI_FURC_LOC_REAPER_RAWL_MARKET = "收割者之境, 罗尔卡, 市场",
    SI_FURC_LOC_RIFTEN_ARMOR = "裂谷城, 市场, 制甲匠",
    SI_FURC_LOC_RIVENSPIRE_SHORN_DWI = "破碎尖顶, 断盔城, 死狼旅店",
    SI_FURC_LOC_SELSWEYR_DHA = "龙卫军械库",
    SI_FURC_LOC_SELSWEYR_SENCHAL_MARKET = "森查尔, 市场",
    SI_FURC_LOC_SHADOWFEN_CORIMONT = "科里蒙港",
    SI_FURC_LOC_STONEFALLS_EBONHEART = "黑檀心",
    SI_FURC_LOC_STORMHAVEN_WAY_MERCH = "风暴港, 途歇城, 市场",
    SI_FURC_LOC_SUMMERSET_ALINOR = "阿里诺尔",
    SI_FURC_LOC_SUMMERSET_ALINOR_RIVERSIDE = "夏暮岛，阿里诺尔，市场",
    SI_FURC_LOC_UNDAUNTED = "无畏者飞地^p,在",
    SI_FURC_LOC_VVARDENFELL_ALDRUHN = "奥德鲁恩",
    SI_FURC_LOC_VVARDENFELL_SURAN = "苏兰",
    SI_FURC_LOC_VVARDENFELL_VIVEC = "维威克城",
    SI_FURC_LOC_VVARDENFELL_VIVEC_GQ = "角斗士的住处",
    SI_FURC_LOC_VVARDENFELL_VIVEC_SDI = "圣德林旅店",
    SI_FURC_LOC_WSKYRIM_SOLI_DH = "西天际，独孤城, 龙之炉",
    SI_FURC_TELVANNI_NECROM_FRF = "泰尔瓦尼半岛，死灵之地，安息地装饰品",
    
    SI_FURC_LOOT_HARVEST = "来自收获节点",
    SI_FURC_LOOT_HARVEST_WOOD = "偶尔在木材资源点中发现",
    
    SI_FURC_MENU_HEADER = "- |cD3B830家具|r:",
    SI_FURC_NPC_AUTOMATON = "机械体^n",
    SI_FURC_PART_OF = "物品 <<1>> 的一部分",
    SI_FURC_PLUGIN_SL_ADD_FIVE = "添加 5份 至购物清单",
    SI_FURC_PLUGIN_SL_ADD_ONE = "添加 1份 至购物清单",
    SI_FURC_POST_ITEM = " 输出物品",
    SI_FURC_POST_ITEMSOURCE = " 输出物品来源",
    SI_FURC_POST_MATERIAL = " 输出材料列表",
    SI_FURC_POST_RECIPE = " 输出配方",
    SI_FURC_RANK = "级别 <<1>>",
    SI_FURC_RARITY_EXTREMELYRARE = "绝迹",
    SI_FURC_RARITY_RARE = "稀有",
    SI_FURC_RARITY_VERYRARE = "罕见",
    SI_FURC_REMOVE_FAVE = " 移除收藏",
    SI_FURC_REQUIRES_ACHIEVEMENT = "成就需求 <<1>>",
    SI_FURC_REWARD_RANKED_MAIL = "排行榜，邮件奖励",
    SI_FURC_RUINS = "废墟^p",
    SI_FURC_TOMBS = "墓穴^p",
    SI_FURC_SEEN_IN_GUILDSTORE = "在公会商店看到",
    SI_FURC_SHOW_CROWN_TT = "已隐藏王冠商店物品，点击显示",
    SI_FURC_SHOW_RUMOUR_TT = "已隐藏谣言物品，点击显示",
    
    SI_FURC_SRC_CHESTS = "箱子^P,从",
    SI_FURC_SRC_CLAM_GIANT = "巨蛤^p,从",
    SI_FURC_SRC_CRAFTING = "制造^N,by",
    SI_FURC_SRC_CROWNSTORE = "王冠商店^n,从",
    SI_FURC_SRC_DOLMEN = "暗锚^P,从",
    SI_FURC_SRC_DROP = "掉落^n,从",
    SI_FURC_SRC_DUNG = "地下城^n,从",
    SI_FURC_SRC_EMPTY = "物品来源未知\n尝试重新检索文件 (右键刷新按钮)\n如果物品来源仍未知，且不是扎尼尔·瑟兰当前出售的物品，请给插件作者@berylbones发一封邮件，附上该物品的链接和来源",
    SI_FURC_SRC_FISH = "钓鱼^N,by",
    SI_FURC_SRC_GEYSER = "海渊魔泉^p,从",
    SI_FURC_SRC_HARVEST = "收获节点^N,从",
    SI_FURC_SRC_ITEMPACK = "王冠商店组合包 [<<1>>] ",
    SI_FURC_SRC_LVLUP = "升级奖励^n,从",
    SI_FURC_SRC_MISCHOUSE = "购买住宅时选项",
    SI_FURC_SRC_PICK = "扒窃^N,从",
    SI_FURC_SRC_QUEST = "任务^n,从",
    SI_FURC_SRC_QUEST_DAILY = "日常任务^p,从",
    SI_FURC_SRC_RNDMOB = "随机怪物^p,从",
    SI_FURC_SRC_RUMOUR_ITEM = "该物品被解包发现，但 (截止插件更新) 尚未实装",
    SI_FURC_SRC_RUMOUR_RECIPE = "该配方被解包发现，但 (截止插件更新) 尚未实装",
    SI_FURC_SRC_SAFEBOX = "保险箱^P,从",
    SI_FURC_SRC_SCAMBOX = "王冠宝箱^n,从",
    SI_FURC_SRC_SCRYING = "考古^N,从",
    SI_FURC_SRC_STEAL = "偷取^N,从",
    SI_FURC_SRC_TOT = "望族传奇^P,从",
    
    SI_FURC_STRING_TRADER = "商人",
    SI_FURC_TRADERS_AF = "成就装饰供应商^n,从",
    SI_FURC_TRADERS_ALCHEMISTS = "炼金术士",
    SI_FURC_TRADERS_BGF = "战场家具商^p,从",
    SI_FURC_TRADERS_BLACKSMITHS = "铁匠",
    SI_FURC_TRADERS_CAF = "任意联盟首都的成就装饰供应商^n,从",
    SI_FURC_TRADERS_CARPENTERS = "木工",
    SI_FURC_TRADERS_CLOTHIERS = "制衣匠",
    SI_FURC_TRADERS_COOKS = "大厨",
    SI_FURC_TRADERS_ENCHANTERS = "附魔师",
    SI_FURC_TRADERS_EVENT = "帝都行商^Nd,从",
    SI_FURC_TRADERS_FAUSTINA = "法斯提纳·库里奥",
    SI_FURC_TRADERS_HGF = "家庭用品供应商^n,从",
    SI_FURC_TRADERS_HOLIDAY = "活动限定的成就装饰供应商^n,从",
    SI_FURC_TRADERS_LUXF = "豪华家具商^Nd,从",
    SI_FURC_TRADERS_ROLIS = "罗利斯·哈拉鲁",
    SI_FURC_TRADERS_RAZOUFA_COLL = "发条城，黄铜堡垒，拉祖法",
    SI_FURC_TRADERS_DROPSNOGLASS_COLL = "瓦登费尔，维威克城，莫掉琉璃",
    
    
    SI_FURC_STRING_CANNOT_CRAFT = "你当前无法制造这个",
    SI_FURC_STRING_CONTEXTMENU_DIVIDER = "右键菜单中不使用分隔符？",
    SI_FURC_STRING_CONTEXTMENU_DIVIDER_TT = "默认在右键菜单的插件功能上下添加分隔符，开启后取消分隔符显示",
    SI_FURC_STRING_CONTEXTMENU_INVENTORY = "禁用右键菜单中的插件功能？",
    SI_FURC_STRING_CONTEXTMENU_INVENTORY_TT = "禁用右键菜单中的部分插件功能，如输出材料、添加收藏夹等",
    SI_FURC_STRING_CRAFTABLE_BY = "可以制造:  ",
    SI_FURC_STRING_DUNG = "地下城",
    SI_FURC_STRING_MENU_ADD_ITEMS_NAME = "为已知/未知配方添加图标？",
    SI_FURC_STRING_MENU_ADD_ITEMS_TT = "你应当不会感受到任何延迟",
    SI_FURC_STRING_MENU_CROWN = "王冠商店物品",
    SI_FURC_STRING_MENU_CROWN_DESC = "当你查看家具物品的信息时，家具数据库将自动更新\n部分家具只能通过王冠商店获取\n启用后，将从默认筛选器中剔除王冠商店物品(你还是可以通过在 来源筛选器 中选择 王冠商店 来查看它们)",
    SI_FURC_STRING_MENU_CROWN_N = "隐藏王冠商店物品？",
    SI_FURC_STRING_MENU_DEBUG = "启用debug信息输出",
    SI_FURC_STRING_MENU_DEBUG_TT = "只有启用调试日志记录器时才会生效",
    SI_FURC_STRING_MENU_DEFAULT_DD = "下拉框的默认值",
    SI_FURC_STRING_MENU_DEFAULT_DD_CHAR = "默认角色筛选器",
    SI_FURC_STRING_MENU_DEFAULT_DD_RESET = "关闭UI时重置筛选器？",
    SI_FURC_STRING_MENU_DEFAULT_DD_RESET_TT = "启用时，打开或关闭UI将使得筛选器回归到以下设置 (译注：该功能似乎无效)",
    SI_FURC_STRING_MENU_DEFAULT_DD_SOURCE = "默认来源筛选器",
    SI_FURC_STRING_MENU_DEFAULT_DD_USE = "初始加载界面时，进行以下设置",
    SI_FURC_STRING_MENU_DEFAULT_DD_USE_TT = "初始加载界面时，进行以下设置\n后续开关UI界面不会重置为默认选项",
    SI_FURC_STRING_MENU_DEFAULT_DD_VERSION = "默认版本筛选器",
    SI_FURC_STRING_MENU_DELETE_CHAR_NAME = "删除角色信息",
    SI_FURC_STRING_MENU_DELETE_CHAR_TT = "从数据库中删除指定角色的配方解锁信息\n角色将在下次登录时再次被检索\n如果某角色未解锁任意配方，他将不会出现在下拉选框中",
    SI_FURC_STRING_MENU_DELETE_CHAR_WARNING = "立即清除角色的配方解锁信息？",
    SI_FURC_STRING_MENU_ENABLE_SHOPPINGLIST = "启用集成？",
    SI_FURC_STRING_MENU_FALL_HIDE_BOOKS = "总是隐藏书籍类家具",
    SI_FURC_STRING_MENU_FALL_HIDE_BOOKS_TT = "即使显示所有物品，也隐藏书籍类家具？",
    SI_FURC_STRING_MENU_FALL_HIDE_CROWN = "总是隐藏王冠商店物品",
    SI_FURC_STRING_MENU_FALL_HIDE_CROWN_TT = "即使显示所有物品, 也隐藏王冠商店物品？",
    SI_FURC_STRING_MENU_FALL_HIDE_RUMOUR = "总是隐藏谣言物品",
    SI_FURC_STRING_MENU_FALL_HIDE_RUMOUR_TT = "即使显示所有物品, 也隐藏谣言物品？",
    SI_FURC_STRING_MENU_FALL_HIDE_UI_BUTTON = "隐藏搜索栏上的显示切换按钮？",
    SI_FURC_STRING_MENU_FILTER_ALL_ON_TEXT = "为文本检索添加限制",
    SI_FURC_STRING_MENU_FILTER_ALL_ON_TEXT_TT = "当通过文本检索家具，且关闭所有筛选器时，添加以下限制",
    SI_FURC_STRING_MENU_FILTER_BOOKS = "法师工会书籍",
    SI_FURC_STRING_MENU_FILTER_BOOKS_N = "隐藏书籍类家具？",
    SI_FURC_STRING_MENU_FILTER_BOOKS_TT = "真正的爱书之人对每本书的位置都了如指掌，隐藏所有书籍类家具？",
    SI_FURC_STRING_MENU_FILTERING = "目录筛选",
    SI_FURC_STRING_MENU_FONTSIZE = "字体尺寸",
    SI_FURC_STRING_MENU_FONTSIZE_TT = "修改UI界面中家具信息的字体大小",
    SI_FURC_STRING_MENU_F_ALL_ON_TEXT = "配置筛选",
    SI_FURC_STRING_MENU_HEADER_F_ALL_DESC = "为文本检索配置筛选设置\n以下选项仅当角色、版本、来源筛选器都关闭时，对文本检索起效",
    SI_FURC_STRING_MENU_HEADER_F_ALL_ON_TEXT = "文本检索的筛选设置",
    SI_FURC_STRING_MENU_HEADER_ICONS = "物品栏与银行中图标",
    SI_FURC_STRING_MENU_HIDE_MENU = "隐藏菜单选项？",
    SI_FURC_STRING_MENU_HIDE_MENU_CROWN = "从下拉列表中隐藏'王冠商店'选项？",
    SI_FURC_STRING_MENU_HIDE_MENU_RUMOUR = "从下拉列表中隐藏'谣言物品'选项？",
    SI_FURC_STRING_MENU_HIDE_MENU_TT = "从下拉列表中隐藏'王冠商店'和'谣言物品'\n王冠商店默认启用\n需要重新加载UI",
    SI_FURC_STRING_MENU_IT_THIS_ONLY = "仅作用于当前角色？",
    SI_FURC_STRING_MENU_IT_THIS_ONLY_TT = "否则为全局账户配置",
    SI_FURC_STRING_MENU_IT_UNKNOWN_NAME = "仅标记未知配方？",
    SI_FURC_STRING_MENU_LUXURY = "豪华物品",
    SI_FURC_STRING_MENU_LUXURY_N = "把豪华物品归类为可购买？",
    SI_FURC_STRING_MENU_LUXURY_TT = "把扎尼尔·瑟兰出售的所有家具归类于可购买筛选器",
    SI_FURC_STRING_MENU_LUXURY_WARN = "需要重新加载UI",
    SI_FURC_STRING_MENU_RESCAN_RUMOUR_NAME = "重新检索谣言物品",
    SI_FURC_STRING_MENU_RESCAN_RUMOUR_TT = "将根据更新后的列表更新谣言物品",
    SI_FURC_STRING_MENU_RESET_DB_NAME = "|cFF0000重置数据库",
    SI_FURC_STRING_MENU_RESET_DB_TT = "这将重置家具数据库",
    SI_FURC_STRING_MENU_RESET_DB_WARNING = "所有数据将被重置，仅当前角色的配方解锁信息将被清除",
    SI_FURC_STRING_MENU_RUMOUR = "谣言物品",
    SI_FURC_STRING_MENU_RUMOUR_DESC = "家具数据库中包含部分作者解包出的物品\n但其中部分家具仍未被实装\n启用后，将从默认筛选器中剔除谣言物品(你还是可以通过在 来源筛选器 中选择 谣言物品 来查看它们)",
    SI_FURC_STRING_MENU_RUMOUR_N = "隐藏谣言物品？",
    SI_FURC_STRING_MENU_SCAN_CHAR_NAME = "检索角色信息",
    SI_FURC_STRING_MENU_SCAN_CHAR_TT = "将检索当前角色已解锁的配方，并更新数据库",
    SI_FURC_STRING_MENU_SCAN_FILES_NAME = "检索文件",
    SI_FURC_STRING_MENU_SCAN_FILES_TT = "将完整检索 Furniture Catalogue 文件中数据",
    SI_FURC_STRING_MENU_SHOWICONONLEFT = "在家具配方左侧显示已知/未知图标？",
    SI_FURC_STRING_MENU_SHOWICONONLEFT_TT = "在物品栏中的家具配方左侧显示绿勾或红叉",
    SI_FURC_STRING_MENU_SKIP_INITIALSCAN = "跳过初始化检索？",
    SI_FURC_STRING_MENU_SKIP_INITIALSCAN_TT = "启用后，在角色登录时不进行已解锁配方信息的检索",
    SI_FURC_STRING_MENU_STARTSILENT = "静默启动？",
    SI_FURC_STRING_MENU_STARTSILENT_TT = "抑制启动信息",
    SI_FURC_STRING_MENU_TOOLTIP = "启用悬浮信息栏增强？",
    SI_FURC_STRING_MENU_TOOLTIP_COLOR = "着色高亮部分信息？",
    SI_FURC_STRING_MENU_TOOLTIP_COLOR_TT = "将高亮'can'和'cannot'单词，在汉化后该功能无效",
    SI_FURC_STRING_MENU_TOOLTIP_DATEFORMAT = "偏好的日期格式",
    SI_FURC_STRING_MENU_TOOLTIP_DATEFORMAT_TT = "影响豪华家具的信息显示",
    SI_FURC_STRING_MENU_TOOLTIP_HIDE_KNOWN = "隐藏已知配方物品",
    SI_FURC_STRING_MENU_TOOLTIP_HIDE_KNOWN_TT = "不显示'可以制作...'的信息",
    SI_FURC_STRING_MENU_TOOLTIP_HIDE_MATERIAL = "隐藏物品的制作材料？",
    SI_FURC_STRING_MENU_TOOLTIP_HIDE_SOURCE = "隐藏物品的来源信息？",
    SI_FURC_STRING_MENU_TOOLTIP_HIDE_STATION = "隐藏物品的制造站类别？",
    SI_FURC_STRING_MENU_TOOLTIP_HIDE_UNKNOWN = "隐藏未知配方物品",
    SI_FURC_STRING_MENU_TOOLTIP_HIDE_UNKNOWN_TT = "不显示'无法制作...'的信息",
    SI_FURC_STRING_MENU_USETINY = "使用简易界面？",
    SI_FURC_STRING_MENU_USETINY_TT = "使用更简易的界面\n你也可以在UI界面中点击 +/- 按钮来切换",
    
    SI_FURC_STRING_PART_OF_COLL = "藏品的一部分",
    SI_FURC_STRING_PIECES = "<<1>> 部件", -- used for scrying
    SI_FURC_STRING_RECIPELEARNED = "学习的配方: <<1>> <<2>> <<3>>",
    SI_FURC_STRING_RECIPESFORCHAR = "<<1>> 的配方",
    SI_FURC_STRING_REWARD = "奖励^n,从",
    SI_FURC_STRING_REWARD_FOR = "<<1>> 的奖励",
    SI_FURC_STRING_WEEKEND_AROUND = "时间点 <<1>>",
    SI_FURC_TEXTBOX_FILTER_DEFAULT = "文本搜索筛选",
    SI_FURC_TOGGLE_SHOPPINGLIST = " 切换购物清单",
    
    SI_FURC_VERBOSE_DB_UPTODATE = "Furniture Catalogue: 数据库已更新",
    SI_FURC_VERBOSE_SCANNING_CHARS = "检索角色已解锁配方信息...",
    SI_FURC_VERBOSE_SCANNING_DATA_FILE = "Furniture Catalogue: 检索文件数据...",
    SI_FURC_VERBOSE_STARTUP = "Furniture Catalogue: 如果你缺失了任意配方，请点击UI界面中的刷新按钮来检索家具制作信息",
  }
  
  --Special Setting
  BB.SetGlobalHook(function()
      for stringId, stringValue in pairs(strings) do
        ZO_CreateStringId(stringId, stringValue)
        SafeAddVersion(stringId, 2)
      end
    end, "FurC", "Constants"
  )

end end

BB.AddonList["FurnitureCatalogue"] = function() if not FurC then return false end
  local dict = {
    ["Click to say thank you:\nLeft: 2k\nRight: 10k\nMiddle: 25k\nYour feedback and/or donation is appreciated!"] = "向作者捐赠金币\n(左键) 2k金币\n(右键) 10k金币\n(中键) 25k金币\n欢迎反馈问题和捐赠！",
    ["number of recipes below"] = "下方的配方数量",
    ["Hide window"] = "隐藏窗口",
    ["Click: Scan character knowledge to database\n\nRight-click: Re-scans data files\n\nMiddle-click: Re-create database (will ask you first)"] = "(左键) 检索当前角色解锁的配方\n(右键) 重新检索数据文件\n(中键) 重建数据库",
    ["change template"] = "改变显示模式",
    ["Filter: Knowledge and source"] = "筛选器: 获取方式",
    ["Filter: game version"] = "筛选器: 游戏版本",
    ["Filter: Character"] = "筛选器: 角色",
  }
  local OldFun = FurC.GuiShowTooltip
  
  FurC.GuiShowTooltip = function(control, tooltiptext, reAnchor)
    tooltiptext = dict[tooltiptext] or tooltiptext
    return OldFun(control, tooltiptext, reAnchor)
  end
  
  local replaceLists = {
    ["name"] = {
      ["Furniture Shopping List"] = "该功能需安装 Furniture Shopping List 插件",
      ["Performance"] = "性能",
      ["User Interface"] = "交互界面",
      ["Rumour Recipes"] = "谣言物品",
      ["Crown store"] = "王冠商店",
      ["Tooltip"] = "悬浮信息栏",
    }
  }
  
  BB.SetMenuReplace("FurC_OptionsPanel", replaceLists)
  BB.SetKeybindingsReplace("TOGGLE_FURNITURE_CATALOGUE", "开关UI界面")
  BB.SetKeybindingsReplace("TOGGLE_FURNITURE_CATALOGUE_RECIPE", "开关家具制造材料显示")
  BB.SetKeybindingsReplace("FURC_CONCAT_TO_TEXTBOX", "添加至 |cFF3333FurCDev|r 文本框")
  
return true end