local BB = MABabel
--[[ 
BB.AddonList[""] = function() if not  then return false end
return true end

do if not BB.SV.BanList[""] then
end end
BB.AddonList[""] = function() if not  then return false end
return true end
]]

BB.AddonList["PersonalAssistant"] = function() if not PersonalAssistant then return false end
  --[[
  Translation Files:
    \localization\en.lua
  ]]
  local PAC = PersonalAssistant.Constants
  local strings = {
    --GenericStrings
    SI_PA_SUBMENU_PAB = "PA 银行",
    SI_PA_SUBMENU_PAJ = "PA 垃圾",
    SI_PA_SUBMENU_PACO = "PA 消耗品", 
    SI_KEYBINDINGS_CATEGORY_PA_BANKING = "|cFFD700P|rersonal|cFFD700A|rssistant 银行",
    SI_KEYBINDINGS_CATEGORY_PA_JUNK = "|cFFD700P|rersonal|cFFD700A|rssistant 垃圾",
    
    --Junk
    SI_PA_MENU_JUNK_AUTO_LAUNDER_HEADER = "自动洗白",
    SI_PA_MENU_JUNK_AUTO_LAUNDER = "在销赃者处自动洗白？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_LOCKPICKS = "自动洗白 开锁器？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_INGREDIENTS = "自动洗白 炼金溶剂？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_MATERIALS = "自动洗白 材料和原材料？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_CRAFTING_BOOSTERS = "自动洗白 品质提升材料？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_ENCHANTING_RUNES = "自动洗白 炼金符文石？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_GLYPHS = "自动洗白 雕文？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_FURNISHING = "自动洗白 家具？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_SOULGEMS = "自动洗白 灵魂石？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_TREASURES = "自动洗白 宝藏？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_TREASURE_MAPS = "自动洗白 藏宝图？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_RECIPES = "自动洗白 食谱和家具图纸？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_MOTIFS = "自动洗白 制作样式书？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_EDICTS = "自动洗白 赦免诏书？",
    SI_PA_MENU_JUNK_AUTO_LAUNDER_CONTAINERS = "自动洗白 容器？",
    SI_PA_CHAT_JUNK_AUTO_LAUNDERED = table.concat({PAC.COLOR.ORANGE_RED:Colorize("洗白"), " %d x %s (花费：%s)"}),

    --Repair
    SI_PA_MENU_REPAIR_REPAIRKIT_GROUP = "使用团队修理包",
    SI_PA_MENU_REPAIR_REPAIRKIT_GROUP_T = "当你组队时进行修理，团队修理包会被优先使用",
    SI_PA_MENU_BUY_REPAIR_KITS_HEADER = "购买修理包",
    SI_PA_MENU_BUY_REPAIR_KITS_ENABLE = "启用自动购买修理包",
    SI_PA_MENU_BUY_ITEM_HEADER = "购买 %s",
    SI_PA_MENU_BUY_ITEM_ENABLE = "自动购买 %s?",
    SI_PA_MENU_BUY_ITEM_ENABLE_T = "当遇到商人时, 缺少的 %s 将被自动购买",
    SI_PA_MENU_BUY_ITEM_THRESHOLD = "%s 库存阈值",
    SI_PA_MENU_BUY_ITEM_THRESHOLD_T = "当你拥有的 %s 的数量低于阈值，缺失部分将被购买",
    SI_PA_MENU_BUY_ITEM_PRIORITY = "%s 货币优先级",
    SI_PA_MENU_BUY_ITEM_PRIORITY_T = "选择当尝试购买 %s 时的货币优先级",	
    SI_PA_MENU_BUY_SOUL_GEMS_HEADER = "购买灵魂石 & 开锁器",
    SI_PA_MENU_BUY_SOUL_GEMS_ENABLE = "启用自动购买灵魂石 & 开锁器",	
    SI_PA_MENU_BUY_SIEGE_ITEMS_HEADER = "购买 "..GetString(SI_ITEMTYPEDISPLAYCATEGORY32),
    SI_PA_MENU_BUY_SIEGE_ITEMS_ENABLE = "启用自动购买 "..GetString(SI_ITEMTYPEDISPLAYCATEGORY32),
    SI_PA_CHAT_BUY_SUMMARY_BOUGHT = "购买 %s x %s 为了 %s",
    SI_PA_CHAT_BUY_SUMMARY_MISSING = "无法购买 %s 以 %s (%s 缺失)",
    
    --Integration
    SI_PA_MENU_INTEGRATION_CK_CHARACTER = "当选中角色已知，则认为该知识已知",
    SI_PA_MENU_INTEGRATION_CK_ENABLE = "启用 Character Knowledge 整合",
    SI_PA_MENU_INTEGRATION_CK_ENABLE_T = table.concat({"使用 Character Knowledge 来决定", GetString("SI_ITEMTYPE", ITEMTYPE_RECIPE), "或", GetString("SI_ITEMTYPE", ITEMTYPE_RACIAL_STYLE_MOTIF), "已知"}),
    SI_PA_MENU_INTEGRATION_CK_INITIALIZING ="Character Knowledge正在启用...",
    
    --Loot
    SI_PA_MENU_LOOT_AUTO_LEARN_RECIPES = table.concat({"自动学习 ", GetString("SI_ITEMTYPE", ITEMTYPE_RECIPE)}),
    SI_PA_MENU_LOOT_AUTO_LEARN_RECIPES_T = table.concat({"当一份 ", GetString("SI_ITEMTYPE", ITEMTYPE_RECIPE), " 被未学习的角色获取，则自动学习"}),	
    SI_PA_MENU_LOOT_AUTO_LEARN_FURNISHING_PLAN = table.concat({"自动学习 ", GetString(SI_PROVISIONERSPECIALINGREDIENTTYPE_TRADINGHOUSERECIPECATEGORY3)}),
    SI_PA_MENU_LOOT_AUTO_LEARN_FURNISHING_PLAN_T = table.concat({"当一份 ", GetString(SI_PROVISIONERSPECIALINGREDIENTTYPE_TRADINGHOUSERECIPECATEGORY3), " 被未学习的角色获取，则自动学习"}),
    SI_PA_MENU_LOOT_SCRIBING_SCRIPTS_HEADER = table.concat({"拾取 ", zo_strformat(GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY_SCRIPT),2),"/",zo_strformat(GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY, 2))}),
    SI_PA_MENU_LOOT_SCRIBING_SCRIPTS_UNKNOWN_MSG = table.concat({">", GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY_SCRIPT).."/"..GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY), "尚未学习"}),
    SI_PA_MENU_LOOT_SCRIBING_SCRIPTS_UNKNOWN_MSG_T = table.concat({"当一份 ", GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY_SCRIPT).."/"..GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY), " 被未学习的角色获取，则自动学习"}),
    SI_PA_MENU_LOOT_AUTO_LEARN_SCRIBING_SCRIPTS = table.concat({"自动学习 ", GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY_SCRIPT)}),
    SI_PA_MENU_LOOT_AUTO_LEARN_SCRIBING_SCRIPTS_T = table.concat({"当一份 ", GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY_SCRIPT), " 被未学习的角色获取，则自动学习"}),
    SI_PA_MENU_LOOT_AUTO_LEARN_SCRIBING_GRIMOIRES = table.concat({"自动学习 ", GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY)}),
    SI_PA_MENU_LOOT_AUTO_LEARN_SCRIBING_GRIMOIRES_T = table.concat({"当一份 ", GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY), " 被未学习的角色获取，则自动学习"}),
    SI_PA_MENU_LOOT_AUTO_LEARN_MOTIFS = table.concat({"自动学习 ", GetString("SI_ITEMTYPE", ITEMTYPE_RACIAL_STYLE_MOTIF)}),
    SI_PA_MENU_LOOT_AUTO_LEARN_MOTIFS_T = table.concat({"当一份 ", GetString("SI_ITEMTYPE", ITEMTYPE_RACIAL_STYLE_MOTIF), " 被未学习的角色获取，则自动学习"}),
    SI_PA_MENU_LOOT_AUTO_LEARN_STYLEPAGES = table.concat({"自动学习 ", GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_CONTAINER_STYLE_PAGE)}),
    SI_PA_MENU_LOOT_AUTO_LEARN_STYLEPAGES_T = table.concat({"当一份 ", GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_CONTAINER_STYLE_PAGE), " 被未学习的角色获取，则自动学习"}),
    SI_PA_MENU_LOOT_APPARELWEAPONS_AUTOBIND = "自动绑定未收藏套装物品",
    SI_PA_MENU_LOOT_APPARELWEAPONS_AUTOBIND_T = table.concat({"当拾取到套装中未收藏的", GetString("SI_ITEMFILTERTYPE", ITEMFILTERTYPE_ARMOR), ",", GetString("SI_ITEMFILTERTYPE", ITEMFILTERTYPE_WEAPONS), "或", GetString("SI_ITEMFILTERTYPE", ITEMFILTERTYPE_JEWELRY), "，自动将其绑定"}),
    SI_PA_MENU_LOOT_ICONS_SCRIBING_HEADER = table.concat({"标记 ", GetString(SI_NOTIFICATIONTYPE20), " ", GetString(SI_ITEMTYPE73), "/", GetString(SI_ITEMTYPE72)}),
    SI_PA_MENU_LOOT_ICONS_SCRIBING_SHOW_KNOWN = table.concat({">", PAC.ICONS.OTHERS.KNOWN.NORMAL, "当一份 ", GetString(SI_NOTIFICATIONTYPE20), " ", GetString(SI_ITEMTYPE73), "/", GetString(SI_ITEMTYPE72), " 已知"}),
    SI_PA_MENU_LOOT_ICONS_SCRIBING_SHOW_UNKNOWN = table.concat({">", PAC.ICONS.OTHERS.UNKNOWN.NORMAL, "当一份 ", GetString(SI_NOTIFICATIONTYPE20), " ", GetString(SI_ITEMTYPE73), "/", GetString(SI_ITEMTYPE72), " 未知"}),
    SI_PA_MENU_LOOT_AUTO_COMBINE_HEADER = table.concat({"当拾取 ", GetString(SI_SPECIALIZEDITEMTYPE109)}), 
    SI_PA_MENU_LOOT_AUTO_COMBINE = "自动组合解锁的收藏品碎片",
    SI_PA_MENU_LOOT_AUTO_COMBINE_T = "自动组合碎片以解锁收藏品",
    SI_PA_MENU_LOOT_AUTO_MARK_AS_JUNK_KNOWN = "自动标记已知物品为垃圾",
    SI_PA_MENU_LOOT_AUTO_MARK_AS_JUNK_KNOWN_T = "自动标记已知物品为垃圾，从而在商人处自动出售",
    SI_PA_ITEM_OTHERUNKNOWN = "其他角色未知",
    
    --worker
    SI_PA_MENU_WORKER_DESCRIPTION = "PAWorker 可自动分解物品或提炼材料",
    SI_PA_MENU_WORKER_METICULOUS_ENABLE = "细致拆装 检查",
    SI_PA_MENU_WORKER_METICULOUS_ENABLE_T = "防止在未装备细致拆装（CP技能）时，进行分解或提炼材料",
    SI_PA_MENU_WORKER_CHECK_EXTRACTION_ENABLE = "提取被动技能 检查",
    SI_PA_MENU_WORKER_CHECK_EXTRACTION_ENABLE_T = "防止在生产材料提取技能未满级时，进行分解或提炼材料",
    SI_PA_MENU_WORKER_AUTOREFINE_HEADER = "自动提炼材料",
    SI_PA_MENU_WORKER_AUTOREFINE_ENABLE = "启用自动提炼材料",
    SI_PA_MENU_WORKER_AUTOREFINE_ENABLE_T = "自动提炼材料",
    SI_PA_MENU_WORKER_AUTODECONSTRUCT_HEADER = "自动分解物品",
    SI_PA_MENU_WORKER_AUTODECONSTRUCT_ENABLE = "启用自动分解物品",
    SI_PA_MENU_WORKER_AUTODECONSTRUCT_ENABLE_T = "自动分解物品",
    SI_PA_MENU_WORKER_PROTECT_BANK_ENABLE = "保护银行物品",
    SI_PA_MENU_WORKER_PROTECT_BANK_ENABLE_T = "为银行物品施加第二道保护",
    SI_PA_MENU_WORKER_PROTECT_UNCOLLECTED_SET_ITEMS_ENABLE = "保护未收集的套装物品",
    SI_PA_MENU_WORKER_PROTECT_UNCOLLECTED_SET_ITEMS_ENABLE_T = "阻止自动分解未收集的套装物品",
    SI_PA_MENU_WORKER_AUTORESEARCHTRAITS_HEADER = "自动研究特质",
    SI_PA_MENU_WORKER_AUTORESEARCHTRAITS_ENABLE = "启用自动研究特质",
    SI_PA_MENU_WORKER_AUTORESEARCHTRAITS_ENABLE_T = "自动研究特质",
    SI_PA_MENU_WORKER_AUTOMARK_QUALITY_THRESHOLD = "自动分解 %s ，若品质等于或低于",
    SI_PA_MENU_WORKER_AUTOMARK_QUALITY_THRESHOLD_T = "自动分解 %s ，若其品质等于或低于所选",
    SI_PA_MENU_WORKER_AUTOMARK_INTRICATE = table.concat({"自动分解 %s [", GetString("SI_ITEMTRAITTYPE", ITEM_TRAIT_TYPE_ARMOR_INTRICATE),"] 特质"}),
    SI_PA_MENU_WORKER_AUTOMARK_INTRICATE_T = table.concat({"自动分解 %s [", GetString("SI_ITEMTRAITTYPE", ITEM_TRAIT_TYPE_ARMOR_INTRICATE), "] 特质（提高制作灵感获得）？"}),
    SI_PA_MENU_WORKER_AUTOMARK_ORNATE = table.concat({"自动分解 %s [", GetString("SI_ITEMTRAITTYPE", ITEM_TRAIT_TYPE_ARMOR_ORNATE), "] 特质"}),
    SI_PA_MENU_WORKER_AUTOMARK_ORNATE_T = table.concat({"自动分解 %s [", GetString("SI_ITEMTRAITTYPE", ITEM_TRAIT_TYPE_ARMOR_ORNATE), "] 特质（提高售价）？"}),
    SI_PA_MENU_WORKER_AUTOMARK_INCLUDE_SETS = "分解套装 %s 物品",
    SI_PA_MENU_WORKER_AUTOMARK_INCLUDE_SETS_T = "关闭时，仅当 %s 不属于任何套装时才被分解",
    SI_PA_MENU_WORKER_AUTOMARK_INCLUDE_KNOWN_TRAITS = "分解已知特质 %s 物品",
    SI_PA_MENU_WORKER_AUTOMARK_INCLUDE_KNOWN_TRAITS_T = "关闭时，仅当 %s 为无特质或未知特质时才被分解",
    SI_PA_MENU_WORKER_AUTOMARK_INCLUDE_UNKNOWN_TRAITS = "分解未知特质 %s 物品",
    SI_PA_MENU_WORKER_AUTOMARK_INCLUDE_UNKNOWN_TRAITS_T = "关闭时，仅当 %s 为无特质或已知特质时才被分解",
    SI_PA_CHAT_ITEM_DECONSTRUCTED = "%s 被分解",
    SI_PA_CHAT_ALREADY_GOT_ITEM_WITH_TRAIT = "其他 %s 拥有可研究的 %s 特性，我们将分解这件",
    SI_PA_CHAT_ITEM_REFINED = "%s 被提炼",
    SI_PA_CHAT_ITEM_RESEARCHED = "%s 被用于研究 %s (%s) 特质 为 %s",
    SI_PA_CHAT_RESEARCH_FULL = "无法研究 %s 特质 为 %s ，因为 %s/%s 研究槽已被占用",
    SI_PA_CHAT_RESEARCH_BUSY = "无法研究 %s 特质，因为你已为 %s 研究另一特质",
    SI_PA_CHAT_NO_METICULOUS = "因细致拆装（CP技能）未装备，自动分解/提炼已停止",
    SI_PA_CHAT_NO_EXTRACTION = "因 %s 等级未满，自动分解/提炼已停止",
    SI_PA_CHAT_NO_EXTRACTION_FOR_ITEM = "%s 等级未满，所以 %s 不会被自动分解",
    SI_PA_CHAT_CRAFTING_QUEST = "因为你持有一项进行中的制造任务，自动分解、提炼和研究已停止",
    
    --banking
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_STYLE_PAGE = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, "已知样式书"}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_STYLE_PAGE = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, "未知样式书"}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE72 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE3250 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_PRIMARY)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE3251 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_SECONDARY)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE3252 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_TERTIARY)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE171 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_STANDARD_DRINK)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE170 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_STANDARD_FOOD)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE177 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_WOODWORKING_BLUEPRINT_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE175 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_ALCHEMY_FORMULA_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE172 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_BLACKSMITHING_DIAGRAM_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE173 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_CLOTHIER_PATTERN_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE174 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_ENCHANTING_SCHEMATIC_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE178 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_JEWELRYCRAFTING_SKETCH_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_KNOWN_ITEMTYPE176 = table.concat({PAC.ICONS.OTHERS.KNOWN.NORMAL, " 已知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_DESIGN_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE72 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_ITEMTYPE", ITEMTYPE_CRAFTED_ABILITY)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE3250 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_PRIMARY)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE3251 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_SECONDARY)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE3252 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_TERTIARY)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE171 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_STANDARD_DRINK)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE170 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_STANDARD_FOOD)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE177 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_WOODWORKING_BLUEPRINT_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE175 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_ALCHEMY_FORMULA_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE172 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_BLACKSMITHING_DIAGRAM_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE173 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_CLOTHIER_PATTERN_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE174 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_ENCHANTING_SCHEMATIC_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE178 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_JEWELRYCRAFTING_SKETCH_FURNISHING)}),
    SI_PA_MENU_BANKING_ADVANCED_UNKNOWN_ITEMTYPE176 = table.concat({PAC.ICONS.OTHERS.UNKNOWN.NORMAL, " 未知 "..GetString("SI_SPECIALIZEDITEMTYPE", SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_DESIGN_FURNISHING)}),
  }
  
  for key, value in pairs(strings) do
    ZO_CreateStringId(key, value)
    SafeAddVersion(key, 1)
  end
  
return true end