local BB = MABabel
--[[ 
BB.AddonList[""] = function() if not  then return false end
return true end

do if not BB.SV.BanList[""] then
end end
BB.AddonList[""] = function() if not  then return false end
return true end
]]

BB.AddonList["VotansMiniMap"] = function() if not VOTANS_MINIMAP then return false end
  --\lang\strings.lua
  ZO_CreateStringId("SI_KEYBINDINGS_CATEGORY_VOTANS_MINIMAP", "小地图")
  ZO_CreateStringId("SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW", "切换显示地图")
  ZO_CreateStringId("SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_HUD", "切换显示HUD")
  ZO_CreateStringId("SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_SIEGE_HUD", "切换显示攻城器")
  ZO_CreateStringId("SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_COMBAT", "切换战斗中显示地图")
  ZO_CreateStringId("SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_OUT", "最小")
  ZO_CreateStringId("SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_IN", "最大")
  ZO_CreateStringId("SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_PLUS", "放大")
  ZO_CreateStringId("SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_MINUS", "缩小")

  ZO_CreateStringId("SI_VOTANSMINIMAP_WORLD_MAP_TWEAKS", "世界地图调整")
  ZO_CreateStringId("SI_VOTANSMINIMAP_WORLD_MAP_TWEAKS_TOOLTIP", "启用调整功能，在一段时间内分散 CPU 负荷。")
  ZO_CreateStringId("SI_VOTANSMINIMAP_MINI_MAP", "小地图")
  ZO_CreateStringId("SI_VOTANSMINIMAP_MINI_MAP_TOOLTIP", "启用内置地图的小地图功能")
  ZO_CreateStringId("SI_VOTANSMINIMAP_APPLY_BUTTON", "应用")
  ZO_CreateStringId("SI_VOTANSMINIMAP_LOCK_POSITION", "锁定位置和尺寸")
  ZO_CreateStringId("SI_VOTANSMINIMAP_LOCK_POSITION_TOOLTIP", "使窗口不能被移动和缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZOOM", "缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZOOM_TOOLTIP", "相对于原始地图分辨率的缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_MOUNTED_ZOOM", "骑乘时缩放比例")
  ZO_CreateStringId("SI_VOTANSMINIMAP_MOUNTED_ZOOM_TOOLTIP", "在坐骑上的相对缩放系数。值1为保持目前缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SUB_ZONE_ZOOM", "子区域缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SUB_ZONE_ZOOM_TOOLTIP", "如果在子区域内，相对于原始地图分辨率的缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_DUNGEON_ZOOM", "地下城缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_DUNGEON_ZOOM_TOOLTIP", "如果在地下城，相对于原始地图分辨率的缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_BG_ZOOM", "战场缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_BG_ZOOM_TOOLTIP", "如果在战场，相对于原始地图分辨率的缩放")
  ZO_CreateStringId("SI_VOTANSMINIMAP_UNIT_PINS_MINIMUM_SIZE", "单位图标最小尺寸")
  ZO_CreateStringId("SI_VOTANSMINIMAP_UNIT_PINS_MINIMUM_SIZE_TOOLTIP", "单位图标缩放不会小于该系数")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_MAP", "显示地图")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_MAP_TOOLTIP", "总是显示小地图")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_HUD", "在HUD中显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_HUD_TOOLTIP", "在世界行走时显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_LOOTING", "拾取掉落时显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_LOOTING_TOOLTIP", "减少隐藏和显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZOOM_TO_PLAYER", "将世界地图缩放到玩家")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZOOM_TO_PLAYER_TOOLTIP", "最大或最小缩放时显示世界地图")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_MOUNTED", "当骑乘时显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_MOUNTED_TOOLTIP", "在坐骑上时显示。该选项优先级高于战斗中显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_COMBAT", "战斗中显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_COMBAT_TOOLTIP", "当处于战斗中显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_SIEGE", "攻城器时显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_SIEGE_TOOLTIP", "当操作攻城器时显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_KEYBINDINGS_ZOOM", "缩放快捷键")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZOOM_OUT", "缩小")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZOOM_OUT_TOOLTIP", "缩小按键的缩放系数\n(按住键位)")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZOOM_IN", "放大")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZOOM_IN_TOOLTIP", "放大按键的缩放系数\n(按住键位)")
  ZO_CreateStringId("SI_VOTANSMINIMAP_APPEARANCE", "外观")
  ZO_CreateStringId("SI_VOTANSMINIMAP_BORDER_STYLE", "边框样式")
  ZO_CreateStringId("SI_VOTANSMINIMAP_BORDER_OPACITY", "边框不透明度")
  ZO_CreateStringId("SI_VOTANSMINIMAP_TITLE_FONT", "标题字体")
  ZO_CreateStringId("SI_VOTANSMINIMAP_TITLE_FONT_SIZE", "标题字体大小")
  ZO_CreateStringId("SI_VOTANSMINIMAP_TITLE_COLOR", "标题颜色")
  ZO_CreateStringId("SI_VOTANSMINIMAP_TITLE_POSITION", "标题位置")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_FULL_TITLE", "显示完整标题")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_FULL_TITLE_TOOLTIP", "显示完整标题。包括活动名称和难度，对于小地图窗口可能过长")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_CLOCK", "显示时钟")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_CLOCK_TOOLTIP", "在小地图中显示时钟")
  ZO_CreateStringId("SI_VOTANSMINIMAP_TIME_FORMAT", "时间格式")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_CLOCK0", "关闭")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_CLOCK1", "现实时间")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_CLOCK2", "游戏内时间")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_CLOCK3", "现实和游戏内时间")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ALLOW_FLOOR_NAVIGATION", "允许楼层导航")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ALLOW_FLOOR_NAVIGATION_TOOLTIP", "如果地图有楼层，则在小地图上显示楼层导航按钮")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZONE_CHANGE_ALERT", "区域变更警报")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_COMPASS", "显示/隐藏 罗盘")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_COMPASS_TOOLTIP", "如果显示小地图，则显示或隐藏罗盘，或者保持原样，让其他插件改变罗盘的可见性")
  ZO_CreateStringId("SI_VOTANSMINIMAP_FRAMEDROP_DEBUG", "框架调试")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_FREEZE_WARNING", "显示冻结警告")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_FREEZE_WARNING_TOOLTIP", "如果操作超过 60fps 的帧时间，则显示警告")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_CAMERA_HEADING", "显示游戏镜头朝向")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_CAMERA_HEADING_TOOLTIP", "在世界地图和小地图上，显示游戏镜头朝向")
  ZO_CreateStringId("SI_VOTANSMINIMAP_CAMERA_HEADING_ANGLE", "标记角度")
  ZO_CreateStringId("SI_VOTANSMINIMAP_CAMERA_HEADING_ANGLE_TOOLTIP", "标记线的角度")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_ON_TOP", "置顶显示")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_ON_TOP_TOOLTIP", "使小地图显示在其他元素上方")

  ZO_CreateStringId("SI_VOTANSMINIMAP_ZONEALERTMODE_ALWAYS", "总是")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZONEALERTMODE_MAP_HIDDEN", "隐藏小地图")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ZONEALERTMODE_NEVER", "从不")
  ZO_CreateStringId("SI_VOTANSMINIMAP_COMPASSMODE_UNTOUCHED", "保持原样")
  ZO_CreateStringId("SI_VOTANSMINIMAP_COMPASSMODE_HIDDEN", "隐藏")
  ZO_CreateStringId("SI_VOTANSMINIMAP_COMPASSMODE_SHOWN", "显示")

  ZO_CreateStringId("SI_VOTANSMINIMAP_KEEP_SQUARE", "保持方形")
  ZO_CreateStringId("SI_VOTANSMINIMAP_KEEP_SQUARE_TOOLTIP", "保持地图区域为正方形。默认。")

  ZO_CreateStringId("SI_BINDING_NAME_VOTANS_TOGGLE_MAP_OFFSET_FIX", "切换固定的小地图位置")

  ZO_CreateStringId("SI_VOTANSMINIMAP_ASYNC_UPDATE", "异步更新")
  ZO_CreateStringId("SI_VOTANSMINIMAP_ASYNC_UPDATE_TOOLTIP", "开（帧速率高于更新）；关（帧速率低于更新）")

  ZO_CreateStringId("SI_VOTANSMINIMAP_PINSIZE_KEEP_FAST_TRAVEL", "传送神龛")
  ZO_CreateStringId("SI_VOTANSMINIMAP_PINSIZE_KEEPS", "要塞")
  ZO_CreateStringId("SI_VOTANSMINIMAP_PINSIZE_DISTRICTS", "区域")
  
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_ALL_TRAVEL_NODES", "显示所有路点神龛")
  ZO_CreateStringId("SI_VOTANSMINIMAP_SHOW_IN_SETTINGS", "在设置界面预览小地图")
  ZO_CreateStringId("SI_VOTANSMINIMAP_GRID_X", "预览位置 - X轴")
  ZO_CreateStringId("SI_VOTANSMINIMAP_GRID_Y", "预览位置 - Y轴")
  ZO_CreateStringId("SI_VOTANSMINIMAP_GRID_W", "预览尺寸 - 宽度")
  ZO_CreateStringId("SI_VOTANSMINIMAP_GRID_H", "预览尺寸 - 高度")
  ZO_CreateStringId("SI_VOTANSMINIMAP_GRID_TOOLTIP", "也可通过鼠标拖拽改变尺寸和位置")
  
return true end