--[[$Revision:$
    --------------------------------------------------------------------------------------------------------------
    Do not edit. Generated from ..\translation\en_US.po. For version see SI_GUILDHALLBUTTON_TRANSLATION_VERSION_29
    --------------------------------------------------------------------------------------------------------------
  ]]
ZO_CreateStringId("SI_GUILDHALLBUTTON_ADD_ON_COMPATIBILITY_IS_AND_7D8F8298C885E6090",'Add-on compatibility is <<1>> and <<2>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_ADD_ON_MENU_CALL_FAILED_00111DF3F9FE114E68529",'Add-on menu call failed:')
ZO_CreateStringId("SI_GUILDHALLBUTTON_ADD_ON_MENU_LIBRARY_LIBADDONMENU_UNAV_B27E5A9",'Add-on menu library LibAddonMenu-2.0 unavailable or is out of date')
ZO_CreateStringId("SI_GUILDHALLBUTTON_ADD_ON_VERSION_IS_5291C2A5F3AB8A534B4548167A0",'Add-on version is <<1>>.<<2>>.<<3>>+<<4>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_AND_NOT_JUST_THEIR_PRINCIPAL_RESIDENC_F5C9A18",'and not just their principal residence. You will get only an error message if you don’t have permission to go there, ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_API_VERSION_IS_004E3AEED6FF731AA19AD7DE9853CE",'API version is <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_ATTEMPT_TO_ESTABLISH_CASTELLAN_OF_GUI_CC4B320",'Attempt to establish castellan of guild no <<1>> id <<2>> failed:')
ZO_CreateStringId("SI_GUILDHALLBUTTON_BUTTON_PRESS_FAILED_58F2A2731EFB8ADB0A00380C7",'Button press failed:')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CAN_T_IDENTIFY_AS_A_GUILD_MEMBER_CHEC_4AB3D5C",'Can’t identify "<<1>>" as a guild member: check spelling and ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CAN_T_IDENTIFY_AS_A_GUILD_MEMBER_CHEC_66E96E4",'Can’t identify "<<1>>" as a guild member: check spelling and capitalization')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CAN_T_IDENTIFY_AS_A_PLAYER_NAME_CHECK_76A9A7C",'Can’t identify "<<1>>" as a player name: check configuration settings')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CAN_T_IDENTIFY_AS_A_PLAYER_NAME_CHECK_861DA12",'Can’t identify "<<1>>" as a player name: check configuration ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CAN_T_IDENTIFY_AS_A_VALID_PLACE_TO_GO_E51FE3A",'Can’t identify <<1>> as a valid place to go')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CAN_T_IDENTIFY_A_SUITABLE_HOUSE_AS_GU_7E3FF7F",'Can’t identify a suitable house as <<1>> guild hall to travel to')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CAN_T_IDENTIFY_THE_GUILD_HALL_YET_D94246312D6",'Can’t identify the guild hall yet')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CAN_T_MATCH_WITH_ANY_HOUSE_NAME_A1F61693F689F",'Can’t match <<1>> with any house name')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CASTELLAN_OFFICER_71F06C6EBA715C8542DCAE0BB06",'Castellan officer')
ZO_CreateStringId("SI_GUILDHALLBUTTON_COMMAND_GUILDHALL_INVALID_EXPECTING_A_209A738",'Command /guildhall <<1>> invalid: expecting a guild number 1..5 (or ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_COMMAND_GUILDHALL_INVALID_EXPECTING_A_6A17FFE",'Command /guildhall <<1>> invalid: expecting a guild number 1..5 (or nothing)')
ZO_CreateStringId("SI_GUILDHALLBUTTON_COMMAND_GUILDHALL_INVALID_EXPECTING_A_6F6ED75",'Command /guildhall <<1>> invalid: expecting a guild number 1..5 (not ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_COMMAND_GUILDHALL_INVALID_YOU_DO_NOT__8A5B05B",'Command /guildhall <<1>> invalid: you do not have a guild numbered ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_COMMAND_GUILDHALL_INVALID_YOU_DO_NOT__DDF0A2B",'Command /guildhall <<1>> invalid: you do not have a guild numbered <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_CONFIGURATION_REPORT_FAILED_32D073A88E532C36A",'Configuration report failed:')
ZO_CreateStringId("SI_GUILDHALLBUTTON_COULD_NOT_IDENTIFY_AS_A_HOUSE_IGNORIN_8A1AA1C",'Could not identify <<1>> as a house: ignoring it')
ZO_CreateStringId("SI_GUILDHALLBUTTON_COULD_NOT_SET_GUILD_HALL_NAME_FOR_36F4E3BF265",'Could not set guild hall name for <<1>>: ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_DEFAULT_GUILD_HALL_IS_GUILD_LEADER_S__343533A",'Default guild hall is guild leader’s principal residence. Enable override to specify something different.')
ZO_CreateStringId("SI_GUILDHALLBUTTON_DEFAULT_GUILD_HALL_IS_GUILD_LEADER_S__FBB32DB",'Default guild hall is guild leader’s principal residence. Enable ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_DESTINATIONS_201376A014EB6075E874622EAB261986",'Destinations')
ZO_CreateStringId("SI_GUILDHALLBUTTON_DISPLAY_TRACEBACK_N_IN_A_UI_ERROR_WIN_6B73666",'Display traceback n in a UI Error window, n=1..9, newest to oldest')
ZO_CreateStringId("SI_GUILDHALLBUTTON_ENABLE_VISIT_COMMAND_66801F4064B19943409289CA",'Enable /visit command')
ZO_CreateStringId("SI_GUILDHALLBUTTON_END_OF_TRACEBACK_4F6563DA25EEBEA7B9157AD45627",'End of traceback <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_ERROR_WHILE_EXECUTING_COMMAND_E6CC53DD796BE01",'Error while executing command ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_ERROR_WHILE_EXECUTING_COMMAND_VISIT_B6388D7B9",'Error while executing command /visit ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_EX_GUILD_96D2B2882E8EAF999C8D4AED6505588C_000",'ex-guild')
ZO_CreateStringId("SI_GUILDHALLBUTTON_FAILED_TO_PROCESS_JOINED_GUILD_EVENT_2D458D53",'Failed to process joined-guild event:')
ZO_CreateStringId("SI_GUILDHALLBUTTON_FAILED_TO_PROCESS_JOINED_GUILD_EVENT_A0F9509C",'Failed to process joined-guild event: ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_FAILED_TO_PROCESS_LEFT_GUILD_EVENT_92EF764328",'Failed to process left-guild event:')
ZO_CreateStringId("SI_GUILDHALLBUTTON_FAILED_TO_PROCESS_LEFT_GUILD_EVENT_BD8C059BAB",'Failed to process left-guild event: ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_FAILED_TO_RETRIEVE_CONFIGURED_HOUSE_N_664FB85",'Failed to retrieve configured house name:')
ZO_CreateStringId("SI_GUILDHALLBUTTON_FAILED_TO_RETRIEVE_CONFIGURED_HOUSE_N_7BFA8A6",'Failed to retrieve configured house name: ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GH_58C1A39F0D84CF0A66EE05448A7267A7_000000000",'/gh')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GH_TRACEBACK_B5CC4EC82980C9D53FE5E3B1FE5E885B",'/gh traceback')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILDHALL_5C3DEEE0E8CAB6EB2989E7B210FEC61B_00",'/guildhall')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILDHALL_E92A91F2910C5C17F2B63FBB99F866D3_00",'/guildhall <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILDHALL_F5F658A21522BF8EEB59D12485DD8A58_00",'/guildhall <<1>> <<2>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_186E1B907496E328562844EA16A01BA8_000000",'Guild <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_BD3549AC09EB9DD7E98ADC80BBC51E87_0",'<<1>> Guild Hall')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_BUTTON_A1BB155E045F550CBF963FAAE85",'Guild Hall Button')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_BUTTON_CANNOT_REGISTER_ANY_154E1C7",'Guild Hall Button cannot register <<1[any/the following/the ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_BUTTON_CANNOT_REGISTER_ANY_8D488C2",'Guild Hall Button cannot register <<1[any/the following/the following]>> slash <<1[command/command/commands]>> due to <<1[conflicts/a conflict/conflicts]>>: <<2>> will not work as described because <<1[it has/it has/they have]>> been registered by the game or <<1[.../another add-on/other add-ons]>>.')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_BUTTON_TRACEBACK_FROM_97C6E05173B0",'Guild Hall Button traceback <<1>> from <<2>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_BUTTON_TRACEBACK_FROM_IDEN_74242CC",'Guild Hall Button traceback <<1>> from <<2>>: identical to traceback <<3>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_BUTTON_TRACEBACK_FROM_IDEN_EB02DB1",'Guild Hall Button traceback <<1>> from <<2>>: identical to traceback ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_CEFFA39898CBD2ACE5339DBB4750CCF9_0",'Guild Hall <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_DAA0E11C3F5AD09A5CFA0E3E5F7CE0E0_0",'Guild Hall')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_HALL_G_3253A38A280D24AF21D3D09AFF0ACFCA",'Guild Hall <<G:1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_LEADER_282636F0BFB2DA3BE6370AD4EA292296",'guild leader')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_LEADER_90E5A1A286AAA741EC3CE1B060C60ECA",'(guild leader)')
ZO_CreateStringId("SI_GUILDHALLBUTTON_GUILD_LEADER_S_HOUSE_1D20F2D72501178F16DBD137",'guild leader’s house')
ZO_CreateStringId("SI_GUILDHALLBUTTON_IDENTIFIED_AS_HOUSE_ID_E5333A37F7DEC36BA81350",'identified <<1>> as house id <<2>>: <<3>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_IF_IN_DOUBT_LEAVE_THESE_OPTIONS_SWITC_8402CC2",'If in doubt, leave these options switched off.')
ZO_CreateStringId("SI_GUILDHALLBUTTON_LIST_10AE9FC7D453B0DD525D0EDF2EDE7961_0000000",'list')
ZO_CreateStringId("SI_GUILDHALLBUTTON_NAME_OF_GUILD_HALL_8E78D14941704F91BFD3B0A368",'Name of guild hall')
ZO_CreateStringId("SI_GUILDHALLBUTTON_NAME_OF_THE_GUILD_OFFICER_WHO_IS_THE__98E12BC",'Name of the guild officer who is the formal owner of the guild hall')
ZO_CreateStringId("SI_GUILDHALLBUTTON_NO_TRACEBACK_NUMBERED_IS_AVAILABLE_F26D90C3D1",'No traceback numbered <<1>> is available')
ZO_CreateStringId("SI_GUILDHALLBUTTON_OR_IF_YOU_TRY_TO_VISIT_A_HOUSE_THE_PL_4532305",'or if you try to visit a house the player doesn’t own.')
ZO_CreateStringId("SI_GUILDHALLBUTTON_OVERRIDE_DEFAULT_GUILD_HALL_39BCB7E69E761919F",'Override default guild hall')
ZO_CreateStringId("SI_GUILDHALLBUTTON_PRINCIPAL_RESIDENCE_36D90080A5B25024E5AEE830E",'principal residence')
ZO_CreateStringId("SI_GUILDHALLBUTTON_PRINCIPAL_RESIDENCE_78EC4E220CF3D0743E140FA7F",'(principal residence)')
ZO_CreateStringId("SI_GUILDHALLBUTTON_RELOAD_UI_ON_JOINING_A_NEW_GUILD_CA066F65A25F",'Reload UI on joining a new guild')
ZO_CreateStringId("SI_GUILDHALLBUTTON_RELOAD_UI_ON_LEAVING_A_GUILD_B9D56C736C853187",'Reload UI on leaving a guild')
ZO_CreateStringId("SI_GUILDHALLBUTTON_REPORT_ADD_ON_GUILD_CONFIGURATION_C33080ECFDF",'Report add-on guild configuration')
ZO_CreateStringId("SI_GUILDHALLBUTTON_REPORT_ADD_ON_VERSION_AND_COMPATIBILI_AD2F13B",'Report add-on version and compatibility')
ZO_CreateStringId("SI_GUILDHALLBUTTON_SHORT_NAME_MATCHES_N_DIFFERENT_HOUSES_8568A2E",'Short name <<1>> matches <<n:2>> different houses: <<3>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_SPECIFY_WHEN_THE_GUILD_HALL_IS_NOT_TH_3806928",'Specify when the guild hall is not the castellan officer’s principal residence')
ZO_CreateStringId("SI_GUILDHALLBUTTON_SPECIFY_WHEN_THE_GUILD_HALL_IS_NOT_TH_CC3B44E",'Specify when the guild hall is not the castellan officer’s principal ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_SWITCH_ON_TO_AUTOMATICALLY_ISSUE_A_RE_4670B3B",'Switch on to automatically issue a /reloadui command on your behalf after joining a guild. If you join 2 guilds in succession you will get 2 /reloadui commands. This may not be what you want')
ZO_CreateStringId("SI_GUILDHALLBUTTON_SWITCH_ON_TO_AUTOMATICALLY_ISSUE_A_RE_B3BBD1A",'Switch on to automatically issue a /reloadui command on your behalf ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_SWITCH_ON_TO_AUTOMATICALLY_ISSUE_A_RE_E43C442",'Switch on to automatically issue a /reloadui command on your behalf after leaving a guild. If you leave 2 guilds in succession you will get 2 /reloadui commands. This may not be what you want')
ZO_CreateStringId("SI_GUILDHALLBUTTON_SWITCH_ON_TO_ENABLE_THE_VISIT_COMMAND_64BC609",'Switch on to enable the /visit command. This allows you to visit, not just the guild hall, but any player’s house, ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_SWITCH_ON_TO_ENABLE_THE_VISIT_COMMAND_65E801F",'Switch on to enable the /visit command')
ZO_CreateStringId("SI_GUILDHALLBUTTON_THIS_HAPPENS_WHEN_YOU_LOG_OUT_OR_ISSU_4733C41",'This happens when you log out or issue the /reloadui command. ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TO_SEE_THE_TRACEBACK_F9049B53E0EBFA176BE850E8",'to see the traceback: ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRACEBACK_756563A5EFEAF4D400B526843A8570EA_00",'traceback')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRANSLATION_VERSION_298B3874E461321DA828F865C",'$Id: en.lua 911 2022-03-14 22:58:16Z paulk $')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRANSLATION_VERSION_98252F5CD90D00AD9997604D6",'Text Version <<1>> <<2>> <<3>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRAVELING_TO_C_S_HOUSE_AT_A614E93F6DC98ADC724",'Traveling to <<C:1>>’s house at <<2>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRAVELING_TO_C_S_HOUSE_L_C79CEBD4996B18D20E2E",'Traveling to <<C:1>>’s house at <<2>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRAVELING_TO_THE_GUILD_HALL_B279E35A01DA3A10F",'Traveling to the <<1>> guild hall <<2>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRAVELING_TO_YOUR_HOUSE_AT_6182CC27C860F0760D",'Traveling to your house at <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRAVELING_TO_YOUR_HOUSE_L_7AF705F3135F6A1A55B",'Traveling to your house at <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRAVEL_L_F68A5C5D8DBEE3FEC8A44B00F3847891_000",'Travel to <<1>> (<<2>>)')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRAVEL_TO_570AFA648090A8DFA32AE1D5BCC11830_00",'Travel to <<1>> (<<2>>)')
ZO_CreateStringId("SI_GUILDHALLBUTTON_TRAVEL_TO_GUILD_HALL_62037739554C73EFB0A3327B",'Travel to Guild Hall')
ZO_CreateStringId("SI_GUILDHALLBUTTON_VERSION_2AF72F100C356273D46284F6FD1DFC08_0000",'version')
ZO_CreateStringId("SI_GUILDHALLBUTTON_VERSION_INFORMATION_9D11E23779D9604067DD20E35",'Version Information')
ZO_CreateStringId("SI_GUILDHALLBUTTON_VISITING_C_S_HOUSE_D1C9CCB9C9BC05CEA78075A5EB",'Visiting <<C:1>>’s house')
ZO_CreateStringId("SI_GUILDHALLBUTTON_VISITING_C_S_HOUSE_L_BAA1050C3487F904AC18303C",'Visiting <<C:1>>’s house at <<2>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_VISITING_YOUR_HOUSE_L_FEF218F331CFB2D9C49457F",'Visiting your house at <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_VISIT_89B0F4A089D457D7FEC4E29BD987543D_000000",'/visit')
ZO_CreateStringId("SI_GUILDHALLBUTTON_VISIT_ANYONE_S_HOUSE_5082C66C9F0FA0FAEBC5151D",'Visit anyone’s house')
ZO_CreateStringId("SI_GUILDHALLBUTTON_VISIT_A_PLAYER_S_HOUSE_B7AA090447E6AE8E6230A8",'Visit a player’s house')
ZO_CreateStringId("SI_GUILDHALLBUTTON_VISIT_B4C0AE96A2003D3DA92E3A709B854322_000000",'/visit <<1>>')
ZO_CreateStringId("SI_GUILDHALLBUTTON_WHEN_LEAVING_AND_JOINING_GUILDS_64B318ABDED04",'When Leaving and Joining Guilds')
ZO_CreateStringId("SI_GUILDHALLBUTTON_WHEN_YOU_LEAVE_A_GUILD_OR_JOIN_A_NEW__945F71F",'When you leave a guild or join a new one, this screen will not show your changed membership until the next UI reload. ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_WHEN_YOU_LEAVE_A_GUILD_OR_JOIN_A_NEW__E576C17",'When you leave a guild or join a new one, this screen will not show ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_YOU_CAN_CHOOSE_TO_HAVE_THE_GUILD_HALL_320D2F0",'You can choose to have the Guild Hall Button do an automatic UI reload when you leave or join a guild. ')
ZO_CreateStringId("SI_GUILDHALLBUTTON_YOU_CAN_CHOOSE_TO_HAVE_THE_GUILD_HALL_4C21598",'You can choose to have the Guild Hall Button do an automatic UI ')
ZO_CreateStringId("SI_GUILDHALLBUTTON__935DFC8294ACC5E24C96FD80891549B2_00000000000",'<<1>><<2>><<3>><<4>><<5>>')
